import type { Country } from "../data/countries/types";
import type { ChildNativeEntity } from "./childNativeAppBridge";

/** Exact checked-in curatedCountries ID/ISO pairs, extracted without loading
 * the literary catalog. These geographic bindings never admit child content. */
export const childCanonicalGlobeBindings: readonly (readonly [string, string])[] = Object.freeze([
  Object.freeze(["afghanistan", "af"] as const),
  Object.freeze(["albania", "al"] as const),
  Object.freeze(["algeria", "dz"] as const),
  Object.freeze(["andorra", "ad"] as const),
  Object.freeze(["angola", "ao"] as const),
  Object.freeze(["antigua_and_barbuda", "ag"] as const),
  Object.freeze(["argentina", "ar"] as const),
  Object.freeze(["armenia", "am"] as const),
  Object.freeze(["australia", "au"] as const),
  Object.freeze(["austria", "at"] as const),
  Object.freeze(["azerbaijan", "az"] as const),
  Object.freeze(["bahamas", "bs"] as const),
  Object.freeze(["bahrain", "bh"] as const),
  Object.freeze(["bangladesh", "bd"] as const),
  Object.freeze(["barbados", "bb"] as const),
  Object.freeze(["belarus", "by"] as const),
  Object.freeze(["belgium", "be"] as const),
  Object.freeze(["belize", "bz"] as const),
  Object.freeze(["bhutan", "bt"] as const),
  Object.freeze(["bolivia", "bo"] as const),
  Object.freeze(["bosnia", "ba"] as const),
  Object.freeze(["botswana", "bw"] as const),
  Object.freeze(["brazil", "br"] as const),
  Object.freeze(["brunei", "bn"] as const),
  Object.freeze(["bulgaria", "bg"] as const),
  Object.freeze(["burkina_faso", "bf"] as const),
  Object.freeze(["burundi", "bi"] as const),
  Object.freeze(["cambodia", "kh"] as const),
  Object.freeze(["cameroon", "cm"] as const),
  Object.freeze(["canada", "ca"] as const),
  Object.freeze(["cape_verde", "cv"] as const),
  Object.freeze(["central_african_republic", "cf"] as const),
  Object.freeze(["chad", "td"] as const),
  Object.freeze(["chile", "cl"] as const),
  Object.freeze(["china", "cn"] as const),
  Object.freeze(["colombia", "co"] as const),
  Object.freeze(["comoros", "km"] as const),
  Object.freeze(["cook_islands", "ck"] as const),
  Object.freeze(["costa_rica", "cr"] as const),
  Object.freeze(["cote_d_ivoire", "ci"] as const),
  Object.freeze(["croatia", "hr"] as const),
  Object.freeze(["cuba", "cu"] as const),
  Object.freeze(["cyprus", "cy"] as const),
  Object.freeze(["czechia", "cz"] as const),
  Object.freeze(["democratic_republic_of_congo", "cd"] as const),
  Object.freeze(["denmark", "dk"] as const),
  Object.freeze(["djibouti", "dj"] as const),
  Object.freeze(["dominica", "dm"] as const),
  Object.freeze(["dominican_republic", "do"] as const),
  Object.freeze(["ecuador", "ec"] as const),
  Object.freeze(["egypt", "eg"] as const),
  Object.freeze(["el_salvador", "sv"] as const),
  Object.freeze(["england", "gb"] as const),
  Object.freeze(["equatorial_guinea", "gq"] as const),
  Object.freeze(["eritrea", "er"] as const),
  Object.freeze(["estonia", "ee"] as const),
  Object.freeze(["eswatini", "sz"] as const),
  Object.freeze(["ethiopia", "et"] as const),
  Object.freeze(["fiji", "fj"] as const),
  Object.freeze(["finland", "fi"] as const),
  Object.freeze(["france", "fr"] as const),
  Object.freeze(["french_guiana", "gf"] as const),
  Object.freeze(["gabon", "ga"] as const),
  Object.freeze(["gambia", "gm"] as const),
  Object.freeze(["georgia", "ge"] as const),
  Object.freeze(["germany", "de"] as const),
  Object.freeze(["ghana", "gh"] as const),
  Object.freeze(["greece", "gr"] as const),
  Object.freeze(["grenada", "gd"] as const),
  Object.freeze(["guatemala", "gt"] as const),
  Object.freeze(["guinea_bissau", "gw"] as const),
  Object.freeze(["guinea_republic", "gn"] as const),
  Object.freeze(["guyana", "gy"] as const),
  Object.freeze(["haiti", "ht"] as const),
  Object.freeze(["honduras", "hn"] as const),
  Object.freeze(["hong_kong", "hk"] as const),
  Object.freeze(["hungary", "hu"] as const),
  Object.freeze(["iceland", "is"] as const),
  Object.freeze(["india", "in"] as const),
  Object.freeze(["indonesia", "id"] as const),
  Object.freeze(["iran", "ir"] as const),
  Object.freeze(["iraq", "iq"] as const),
  Object.freeze(["ireland", "ie"] as const),
  Object.freeze(["israel", "il"] as const),
  Object.freeze(["italy", "it"] as const),
  Object.freeze(["jamaica", "jm"] as const),
  Object.freeze(["japan", "jp"] as const),
  Object.freeze(["jordan", "jo"] as const),
  Object.freeze(["kazakhstan", "kz"] as const),
  Object.freeze(["kenya", "ke"] as const),
  Object.freeze(["kiribati", "ki"] as const),
  Object.freeze(["kosovo", "xk"] as const),
  Object.freeze(["kuwait", "kw"] as const),
  Object.freeze(["kyrgyzstan", "kg"] as const),
  Object.freeze(["laos", "la"] as const),
  Object.freeze(["latvia", "lv"] as const),
  Object.freeze(["lebanon", "lb"] as const),
  Object.freeze(["lesotho", "ls"] as const),
  Object.freeze(["liberia", "lr"] as const),
  Object.freeze(["libya", "ly"] as const),
  Object.freeze(["liechtenstein", "li"] as const),
  Object.freeze(["lithuania", "lt"] as const),
  Object.freeze(["luxembourg", "lu"] as const),
  Object.freeze(["macau", "mo"] as const),
  Object.freeze(["madagascar", "mg"] as const),
  Object.freeze(["malawi", "mw"] as const),
  Object.freeze(["malaysia", "my"] as const),
  Object.freeze(["maldives", "mv"] as const),
  Object.freeze(["mali", "ml"] as const),
  Object.freeze(["malta", "mt"] as const),
  Object.freeze(["marshall_islands", "mh"] as const),
  Object.freeze(["mauritania", "mr"] as const),
  Object.freeze(["mauritius", "mu"] as const),
  Object.freeze(["mexico", "mx"] as const),
  Object.freeze(["micronesia", "fm"] as const),
  Object.freeze(["moldova", "md"] as const),
  Object.freeze(["monaco", "mc"] as const),
  Object.freeze(["mongolia", "mn"] as const),
  Object.freeze(["montenegro", "me"] as const),
  Object.freeze(["morocco", "ma"] as const),
  Object.freeze(["mozambique", "mz"] as const),
  Object.freeze(["myanmar", "mm"] as const),
  Object.freeze(["namibia", "na"] as const),
  Object.freeze(["nauru", "nr"] as const),
  Object.freeze(["nepal", "np"] as const),
  Object.freeze(["netherlands", "nl"] as const),
  Object.freeze(["new_zealand", "nz"] as const),
  Object.freeze(["nicaragua", "ni"] as const),
  Object.freeze(["niger", "ne"] as const),
  Object.freeze(["nigeria", "ng"] as const),
  Object.freeze(["niue", "nu"] as const),
  Object.freeze(["north_korea", "kp"] as const),
  Object.freeze(["north_macedonia", "mk"] as const),
  Object.freeze(["norway", "no"] as const),
  Object.freeze(["oman", "om"] as const),
  Object.freeze(["pakistan", "pk"] as const),
  Object.freeze(["palau", "pw"] as const),
  Object.freeze(["palestine", "ps"] as const),
  Object.freeze(["panama", "pa"] as const),
  Object.freeze(["papua_new_guinea", "pg"] as const),
  Object.freeze(["paraguay", "py"] as const),
  Object.freeze(["peru", "pe"] as const),
  Object.freeze(["philippines", "ph"] as const),
  Object.freeze(["poland", "pl"] as const),
  Object.freeze(["portugal", "pt"] as const),
  Object.freeze(["puerto_rico", "pr"] as const),
  Object.freeze(["qatar", "qa"] as const),
  Object.freeze(["republic_of_congo", "cg"] as const),
  Object.freeze(["romania", "ro"] as const),
  Object.freeze(["russia", "ru"] as const),
  Object.freeze(["rwanda", "rw"] as const),
  Object.freeze(["saint_kitts_and_nevis", "kn"] as const),
  Object.freeze(["saint_lucia", "lc"] as const),
  Object.freeze(["saint_vincent_and_the_grenadines", "vc"] as const),
  Object.freeze(["samoa", "ws"] as const),
  Object.freeze(["san_marino", "sm"] as const),
  Object.freeze(["sao_tome_and_principe", "st"] as const),
  Object.freeze(["senegal", "sn"] as const),
  Object.freeze(["serbia", "rs"] as const),
  Object.freeze(["seychelles", "sc"] as const),
  Object.freeze(["sierra_leone", "sl"] as const),
  Object.freeze(["singapore", "sg"] as const),
  Object.freeze(["slovakia", "sk"] as const),
  Object.freeze(["slovenia", "si"] as const),
  Object.freeze(["solomon_islands", "sb"] as const),
  Object.freeze(["somalia", "so"] as const),
  Object.freeze(["south_africa", "za"] as const),
  Object.freeze(["south_korea", "kr"] as const),
  Object.freeze(["south_sudan", "ss"] as const),
  Object.freeze(["spain", "es"] as const),
  Object.freeze(["sri_lanka", "lk"] as const),
  Object.freeze(["sudan", "sd"] as const),
  Object.freeze(["suriname", "sr"] as const),
  Object.freeze(["sweden", "se"] as const),
  Object.freeze(["switzerland", "ch"] as const),
  Object.freeze(["syria", "sy"] as const),
  Object.freeze(["taiwan", "tw"] as const),
  Object.freeze(["tajikistan", "tj"] as const),
  Object.freeze(["tanzania", "tz"] as const),
  Object.freeze(["thailand", "th"] as const),
  Object.freeze(["timor_leste", "tl"] as const),
  Object.freeze(["tonga", "to"] as const),
  Object.freeze(["trinidad_and_tobago", "tt"] as const),
  Object.freeze(["tunisia", "tn"] as const),
  Object.freeze(["turkey", "tr"] as const),
  Object.freeze(["turkmenistan", "tm"] as const),
  Object.freeze(["tuvalu", "tv"] as const),
  Object.freeze(["uae", "ae"] as const),
  Object.freeze(["uganda", "ug"] as const),
  Object.freeze(["ukraine", "ua"] as const),
  Object.freeze(["uruguay", "uy"] as const),
  Object.freeze(["usa", "us"] as const),
  Object.freeze(["uzbekistan", "uz"] as const),
  Object.freeze(["vanuatu", "vu"] as const),
  Object.freeze(["vatican", "va"] as const),
  Object.freeze(["venezuela", "ve"] as const),
  Object.freeze(["vietnam", "vn"] as const),
  Object.freeze(["yemen", "ye"] as const),
  Object.freeze(["zambia", "zm"] as const),
  Object.freeze(["zimbabwe", "zw"] as const),
]);

const codes = new Map(childCanonicalGlobeBindings);
/** Exact IDs only: no alias, case folding, slug or label-derived geography. */
export function childCanonicalCountryCode(id: string): string | undefined {
  return codes.get(id);
}

/** One stable input for the original atlas across profile/locale retirement.
 * No names, biographies, writers, review claims or native capabilities live here. */
export const childCanonicalGlobeAtlasCountries: Country[] = childCanonicalGlobeBindings.map(([id, code]) => {
  const writers: Country["writers"] = [];
  Object.freeze(writers);
  return Object.freeze({ id, code, name: "", description: "", writers });
});
Object.freeze(childCanonicalGlobeAtlasCountries);

/** Caller supplies a freshly native-admitted entity. Geometry adds only the
 * exact code; unknown IDs remain available as native text without a map binding. */
export function projectChildNativeGlobeCountry(node: ChildNativeEntity): Country | null {
  if (node.reference.kind !== "country") return null;
  const code = childCanonicalCountryCode(node.reference.id);
  return { id: node.reference.id, ...(code ? { code } : {}),
    name: node.payload.title, description: node.payload.text, writers: [] };
}

/** Atlas hits and cached hover/keyboard values are identity hints only. Always
 * return the current admitted row; retired or unadmitted copy never survives. */
export function resolveChildGlobeCountry(
  hint: Pick<Country, "id"> | null | undefined, countries: readonly Country[]
): Country | null {
  if (!hint || !codes.has(hint.id)) return null;
  return countries.find(country => country.id === hint.id) ?? null;
}
