package ru.probpera.literaryplanet;

import android.content.Context;
import android.os.Bundle;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import java.nio.charset.StandardCharsets;
import java.util.*;
import org.junit.*;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;

/** AUTHORED_NOT_RUN. Synthetic IDs, text, receipts and OS storage are not release pins. */
@RunWith(AndroidJUnit4.class)
public final class PlanetChildBadgesDownloadsRuntimeTest {
    private final Context context=InstrumentationRegistry.getInstrumentation().getTargetContext();
    private final Bundle args=InstrumentationRegistry.getArguments();
    @Before public void ownRun(){assertEquals("local-v2-child-badges-downloads",args.getString("literaryChildBadgesDownloadsPhase"));assertTrue(args.getString("literaryRunId","").matches("[a-f0-9]{32}"));}
    private interface Work {void run()throws Exception;}
    private static void denied(Work work)throws Exception {boolean refused=false;try{work.run();}catch(Exception unavailable){refused=true;}assertTrue("Unavailable required",refused);}
    private static Map<String,Object> row(Object... fields){Map<String,Object> value=new LinkedHashMap<>();for(int i=0;i<fields.length;i+=2)value.put((String)fields[i],fields[i+1]);return value;}
    private static PlanetChildPassport.Award award(long program,long rule,String trigger)throws Exception {return new PlanetChildPassport.Award("fixture-program",program,"b".repeat(64),"c".repeat(64),"fixture-badge",rule,"journey-one",2,2,trigger,Arrays.asList("node-one","node-two"));}
    private static PlanetChildPassport.Ledger facts()throws Exception {return new PlanetChildPassport.Ledger(Arrays.asList("country-one"),Arrays.asList(new PlanetChildPassport.Credit("journey-one","node-one","writer","writer-one",2,2),new PlanetChildPassport.Credit("journey-one","node-two","work","work-one",2,2)),Arrays.asList(new PlanetChildPassport.CompletedJourney("journey-one",2,2,Arrays.asList("node-one","node-two"))));}
    @Test public void routeSaveWireHasNoBytesUrlsCallerProfilesOrApproval()throws Exception {Map<String,Object> request=row("version",2L,"requestId","1".repeat(32),"contextToken","2".repeat(32),"journeyId","journey-one","expectedRevision",7L);assertEquals(7,PlanetChildDataTransport.decodeV2("saveJourneyRoute",request).expectedRevision);for(String name:Arrays.asList("bytes","url","base64","approved","profileId","programId","snapshotChecksum")){Map<String,Object> extra=new LinkedHashMap<>(request);extra.put(name,"caller");denied(()->PlanetChildDataTransport.decodeV2("saveJourneyRoute",extra));}request.put("expectedRevision",9007199254740990L);denied(()->PlanetChildDataTransport.decodeV2("saveJourneyRoute",request));}
    @Test public void routeSaveReachesPassportCommandDispatch()throws Exception {Map<String,Object> request=row("version",2L,"requestId","1".repeat(32),"contextToken","2".repeat(32),"journeyId","journey-one","expectedRevision",7L);assertTrue(PlanetChildVault.passportCommandMethod(PlanetChildDataTransport.decodeV2("saveJourneyRoute",request).method));assertFalse(PlanetChildVault.passportCommandMethod("openJourney"));assertFalse(PlanetChildVault.passportCommandMethod("readEntity"));}
    @Test public void exporterSourceAdmissionUsesActualModuleAndIndependentPin()throws Exception {Map<String,String> sources=new LinkedHashMap<>();sources.put("src/child/childNativePassportProgramReleasePins.json","4cc9a5d39f2c35fa50d15e60c4dba52263709f751884825d5fbfe4e0062036f0");sources.put("src/child/childNativePassportProgram.ts","a".repeat(64));sources.put("scripts/mobile/native-child-passport-assets.mjs","b".repeat(64));PlanetChildVault.validatePassportProgramSources(sources);Map<String,String> old=new LinkedHashMap<>(sources);old.remove("scripts/mobile/native-child-passport-assets.mjs");old.put("scripts/mobile/native-child-passport-program-assets.mjs","b".repeat(64));denied(()->PlanetChildVault.validatePassportProgramSources(old));sources.put("src/child/childNativePassportProgramReleasePins.json","c".repeat(64));denied(()->PlanetChildVault.validatePassportProgramSources(sources));}
    @Test public void emptyPinsAwardLeafKeepsCompletionWithoutNativeReentry()throws Exception {assertTrue(PlanetChildVault.fixturePassportEmptyAwardLeaf(context));}
    @Test public void legacyCodecHasNoInventedAwardsOrDownloads()throws Exception {PlanetChildPassport.Ledger old=facts();byte[] before=old.encode();try{PlanetChildPassport.Ledger restored=PlanetChildPassport.decode(before);assertTrue(restored.awards.isEmpty());assertTrue(restored.routes.isEmpty());assertArrayEquals(before,restored.encode());assertFalse(PlanetChildPassport.empty().confirms(award(1,1,"completed-learning")));assertFalse(PlanetChildPassport.empty().confirms(award(1,1,"completed-journey")));}finally{Arrays.fill(before,(byte)0);}}
    @Test public void programRuleVersionsRetainDistinctProvenance()throws Exception {PlanetChildPassport.Ledger original=facts(),earned=original.awarded(award(1,1,"completed-learning")).awarded(award(2,1,"completed-learning")).awarded(award(2,2,"completed-learning"));assertEquals(3,earned.awards.size());assertTrue(earned.confirms(earned.awards.get(0)));assertEquals(earned,earned.awarded(earned.awards.get(0)));assertEquals(original.credits,earned.credits);byte[] bytes=earned.encode();try{assertEquals(earned,PlanetChildPassport.decode(bytes));}finally{Arrays.fill(bytes,(byte)0);}}
    @Test public void renewedReviewRetainsDistinctAwardProvenance()throws Exception {PlanetChildPassport.Award original=award(1,1,"completed-learning"),renewed=new PlanetChildPassport.Award("fixture-program",1,"b".repeat(64),"d".repeat(64),"fixture-badge",1,"journey-one",2,2,"completed-learning",Arrays.asList("node-one","node-two"));PlanetChildPassport.Ledger both=facts().awarded(original).awarded(renewed);assertEquals(2,both.awards.size());assertEquals(both,both.awarded(renewed));byte[] bytes=both.encode();try{assertEquals(both,PlanetChildPassport.decode(bytes));}finally{Arrays.fill(bytes,(byte)0);}}
    @Test public void canonicalSnapshotContainsActualNestedFactPayload()throws Exception {byte[] bytes=PlanetChildVault.fixturePassportRouteBytes(context,"journey-one");try{assertEquals("journey-one",PlanetChildVault.validatePassportRouteSnapshot(bytes));assertTrue(new String(bytes,StandardCharsets.UTF_8).contains("Nested text is durable"));PlanetChildPassport.Route route=PlanetChildDataStore.fixturePassportRoute(context,"journey-one");try{assertArrayEquals(bytes,route.copy());PlanetChildPassport.Ledger ledger=facts().saved(route);byte[] encoded=ledger.encode();try{PlanetChildPassport.Ledger restored=PlanetChildPassport.decode(encoded);try{assertEquals(ledger,restored);assertArrayEquals(bytes,restored.routes.get(0).copy());}finally{restored.wipe();}}finally{Arrays.fill(encoded,(byte)0);}}finally{route.wipe();}}finally{Arrays.fill(bytes,(byte)0);}}
    @Test public void snapshotsRejectTrailingNoncanonicalAndMissingClosureBytes()throws Exception {byte[] bytes=PlanetChildVault.fixturePassportRouteBytes(context,"journey-one");try{byte[] trailing=Arrays.copyOf(bytes,bytes.length+1);denied(()->PlanetChildVault.validatePassportRouteSnapshot(trailing));String text=new String(bytes,StandardCharsets.UTF_8);denied(()->PlanetChildVault.validatePassportRouteSnapshot((" "+text).getBytes(StandardCharsets.UTF_8)));denied(()->PlanetChildVault.validatePassportRouteSnapshot(text.replaceFirst("nested-fact","unknown-missing-fact").getBytes(StandardCharsets.UTF_8)));}finally{Arrays.fill(bytes,(byte)0);}}
    @Test public void routeAndAwardCapacityNeverEvictsPriorFacts()throws Exception {PlanetChildPassport.Ledger ledger=facts();try{for(int i=0;i<32;i++)ledger=ledger.saved(PlanetChildDataStore.fixturePassportRoute(context,"route-"+i));assertEquals(32,ledger.routes.size());PlanetChildPassport.Ledger full=ledger;PlanetChildPassport.Route overflow=PlanetChildDataStore.fixturePassportRoute(context,"route-overflow");try{denied(()->full.saved(overflow));assertEquals(32,full.routes.size());assertEquals(facts().credits,full.credits);}finally{overflow.wipe();}PlanetChildPassport.Ledger badges=facts();for(int i=1;i<=256;i++)badges=badges.awarded(award(i,1,"completed-learning"));PlanetChildPassport.Ledger all=badges;assertEquals(256,all.awards.size());denied(()->all.awarded(award(257,1,"completed-learning")));assertEquals(256,all.awards.size());}finally{ledger.wipe();}}
    @Test public void nativeEmptyProgramPinsRejectCallerCatalogAuthority()throws Exception {assertTrue(PlanetChildVault.fixturePassportPinsDeny(context));}
    @Test public void signedProgramReviewLeafRejectsTamperWrongDomainKeysAndExpiredWindow()throws Exception {for(String scenario:Arrays.asList("valid","tampered","wrong-domain","unknown-key","expired-review"))assertTrue(PlanetChildVault.fixturePassportSignedReview(context,scenario));}
    @Test public void detachedResultsPreserveBytesAfterEncryptedStateOwnerCloses()throws Exception {assertTrue(PlanetChildDataStore.fixturePassportRouteScenario(context,"codec"));}
    @Test public void parentDownloadsOnlyPreservesAwardsLearningAndExactSibling()throws Exception {assertTrue(PlanetChildDataStore.fixturePassportRouteScenario(context,"downloads"));assertTrue(PlanetChildVault.fixtureCanonicalDeletion(context,"downloads"));}
    @Test public void parentHistoryAndProfileRemoveRouteBytesAndAwardsOnlyForTarget()throws Exception {assertTrue(PlanetChildDataStore.fixturePassportRouteScenario(context,"history"));assertTrue(PlanetChildDataStore.fixturePassportRouteScenario(context,"profile"));}
    @Test public void corruptStoredSnapshotDeniesWithoutRepair()throws Exception {assertTrue(PlanetChildDataStore.fixturePassportRouteScenario(context,"corrupt"));}
    @Test public void realEncryptedSyntheticRestartAndPendingMarkerRetainDenial()throws Exception {String run=args.getString("literaryRunId");for(String phase:Arrays.asList("write","read","pending","pending-reopen"))assertTrue(PlanetChildDataStore.fixturePassportRoutePersistence(context,run,phase));}
}
