package ru.probpera.literaryplanet;

import static org.junit.Assert.*;
import android.content.Context;
import android.os.Bundle;
import androidx.test.core.app.ActivityScenario;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import java.io.InputStream;
import java.lang.reflect.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicReference;
import org.junit.*;
import org.junit.runner.RunWith;

/** Software codec/storage cases and separately gated actual child admission.
 * No fixture manufactures review, production seed or child permits. */
@RunWith(AndroidJUnit4.class)
public final class PlanetChildJourneyRuntimeTest {
    private final Context context=InstrumentationRegistry.getInstrumentation().getTargetContext();
    private final Bundle args=InstrumentationRegistry.getArguments();
    @Before public void ownRun(){assertEquals("local-v2-child-journey",args.getString("literaryChildJourneyPhase"));assertTrue(args.getString("literaryRunId","").matches("[a-f0-9]{32}"));}
    private interface Work {void run() throws Exception;}
    private static void denied(Work work) throws Exception {boolean denied=false;try{work.run();}catch(Exception failure){denied=true;}assertTrue("Unavailable required",denied);}
    private static String id(){return UUID.randomUUID().toString().replace("-","");}
    private static Map<String,Object> map(Object... values){Map<String,Object> out=new LinkedHashMap<>();for(int i=0;i<values.length;i+=2)out.put((String)values[i],values[i+1]);return out;}
    private static Map<String,Object> base(String token){return map("version",2L,"requestId",id(),"contextToken",token);}
    @SuppressWarnings("unchecked") private static Map<String,Object> row(Object value){assertTrue(value instanceof Map);return (Map<String,Object>)value;}
    private static Object field(Object value,String name) throws Exception {Field field=value.getClass().getDeclaredField(name);field.setAccessible(true);return field.get(value);}
    private static long revision(Object value){assertTrue(value instanceof Number);return ((Number)value).longValue();}
    private static Map<String,Object> data(Map<String,Object> reply){assertEquals("ok",reply.get("status"));return row(reply.get("value"));}

    @Test public void closedJourneyWireDeniesCapabilitiesAndProfileOverride() throws Exception {
        Map<String,Object> open=base("2".repeat(32));open.put("journeyId","fixture-journey");open.put("expectedRevision",0L);assertEquals("fixture-journey",PlanetChildDataTransport.decodeV2("openJourney",open).journeyId);
        for(String forbidden:Arrays.asList("progress","profileId","nodeToken","reference","contentChecksum","approved","url")){Map<String,Object> extra=new LinkedHashMap<>(open);extra.put(forbidden,"caller-proof");denied(()->PlanetChildDataTransport.decodeV2("openJourney",extra));}
        Map<String,Object> bad=new LinkedHashMap<>(open);bad.put("journeyId","https://caller.example/route");denied(()->PlanetChildDataTransport.decodeV2("openJourney",bad));
        Map<String,Object> advance=new LinkedHashMap<>(open);advance.put("currentNodeId",null);advance.put("action","complete");denied(()->PlanetChildDataTransport.decodeV2("advanceJourney",advance));advance.put("action","restart");assertNull(PlanetChildDataTransport.decodeV2("advanceJourney",advance).currentNodeId);
        for(Object value:Arrays.asList(-1L,true,1.5d,9007199254740991L)){Map<String,Object> invalid=new LinkedHashMap<>(open);invalid.put("expectedRevision",value);denied(()->PlanetChildDataTransport.decodeV2("openJourney",invalid));}
    }
    @Test public void typedSemanticProgressAndRevisionsRemainBounded() throws Exception {
        // Independent binary-spec vector, not native execution evidence.
        String goldenHex="4c504a31010009726f7574652d6f6e65000000000000000100000000000000010100086e6f64652d6f6e6502000e7a2d72656d6f7665642d6e6f6465000e612d72656d6f7665642d6e6f646501000b636f756e7472792d6f6e65000001";byte[] golden=new byte[goldenHex.length()/2];for(int i=0;i<golden.length;i++)golden[i]=(byte)Integer.parseInt(goldenHex.substring(i*2,i*2+2),16);assertEquals(93,golden.length);
        PlanetChildJourney.Progress canonical=new PlanetChildJourney.Progress("route-one",1,1,"node-one",Arrays.asList("z-removed-node","a-removed-node"),"country-one",null,null,"journey");byte[] encoded=canonical.encode();try{assertArrayEquals(golden,encoded);assertEquals(canonical,PlanetChildJourney.decode(golden));}finally{Arrays.fill(encoded,(byte)0);Arrays.fill(golden,(byte)0);}
        List<String> nodes=Arrays.asList("fixture-country","fixture-writer","fixture-work");PlanetChildJourney.Progress initial=PlanetChildJourney.reanchor(null,"fixture-journey",1,nodes);assertTrue(initial.completedNodeIds.isEmpty());assertEquals(nodes.get(0),initial.currentNodeId);
        PlanetChildJourney.Progress next=PlanetChildJourney.advance(initial,nodes,nodes.get(0),"complete","country");assertEquals(Arrays.asList(nodes.get(0)),next.completedNodeIds);assertEquals(nodes.get(0),next.selectedCountryId);
        PlanetChildJourney.Progress restarted=PlanetChildJourney.advance(next,nodes,next.currentNodeId,"restart","writer");assertEquals(next.completedNodeIds,restarted.completedNodeIds);assertEquals(nodes.get(0),restarted.currentNodeId);
        PlanetChildJourney.Progress finished=PlanetChildJourney.advance(next,nodes,next.currentNodeId,"complete","writer");finished=PlanetChildJourney.advance(finished,nodes,finished.currentNodeId,"complete","work");assertNull(finished.currentNodeId);assertTrue(finished.completedNodeIds.containsAll(nodes));
        PlanetChildJourney.Progress old=new PlanetChildJourney.Progress("fixture-journey",1,1,"removed-checkpoint",Arrays.asList("retired-completion","fixture-country"),null,null,null,"journey");PlanetChildJourney.Progress migrated=PlanetChildJourney.reanchor(old,"fixture-journey",2,nodes);assertEquals("fixture-country",migrated.currentNodeId);assertEquals(old.completedNodeIds,migrated.completedNodeIds);assertEquals(2,migrated.contentVersion);
        byte[] bytes=migrated.encode();try{assertEquals(migrated,PlanetChildJourney.decode(bytes));byte[] trailing=Arrays.copyOf(bytes,bytes.length+1);denied(()->PlanetChildJourney.decode(trailing));byte[] version=bytes.clone();version[4]=2;denied(()->PlanetChildJourney.decode(version));}finally{Arrays.fill(bytes,(byte)0);}
        denied(()->PlanetChildJourney.validateNodes("fixture-journey",Arrays.asList("fixture-node","fixture-node")));denied(()->PlanetChildJourney.validateNodes("fixture-journey",Arrays.asList("fixture-journey")));denied(()->new PlanetChildJourney.Progress("fixture-journey",1,1,null,Arrays.asList("duplicate","duplicate"),null,null,null,"journey"));
        List<String> full=new ArrayList<>();for(int i=0;i<64;i++)full.add("completed-"+i);PlanetChildJourney.Progress bounded=new PlanetChildJourney.Progress("fixture-journey",1,1,"new-node",full,null,null,null,"journey");denied(()->PlanetChildJourney.advance(bounded,Arrays.asList("new-node"),"new-node","complete","fact"));
    }
    @Test public void legacyAndInactiveJourneySnapshotsRemainExact() throws Exception {for(String scenario:Arrays.asList("legacy","cas","isolation","archive","migration","corrupt","capacity"))assertTrue(scenario,PlanetChildDataStore.fixtureJourneyScenario(context,scenario));}
    @Test public void encryptedJourneyProgressPersistsAcrossReopenWithoutImplicitSeed() throws Exception {
        assertTrue(PlanetChildDataStore.fixtureAppearanceMissingDoesNotSeed(context,id()));String phase=args.getString("literaryChildJourneyPersistencePhase","");Assume.assumeTrue("NOT_RUN: explicit owned AES process phase required",Arrays.asList("write","read","pending","pending-reopen").contains(phase));String run=args.getString("literaryRunId");assertTrue(PlanetChildDataStore.fixtureJourneyPersistence(context,run,phase));assertTrue(PlanetChildDataStore.fixtureJourneyPersistence(context,run,phase.startsWith("pending")?"pending-reopen":"read"));
    }
    private static final class Pending {
        final CountDownLatch returned=new CountDownLatch(1);final AtomicReference<Map<String,Object>> reply=new AtomicReference<>();
        Pending(PlanetChildVault.LocalV2AppOwner owner,String method,Map<String,Object> request) throws Exception {PlanetChildDataTransport.V2Request dto=PlanetChildDataTransport.decodeV2(method,request);InstrumentationRegistry.getInstrumentation().runOnMainSync(()->owner.execute(dto,value->{reply.set(value);returned.countDown();}));}
        Map<String,Object> joined() throws Exception {return joined(10);}Map<String,Object> joined(long seconds) throws Exception {assertTrue("Actual native command joined",returned.await(seconds,TimeUnit.SECONDS));assertNotNull(reply.get());return reply.get();}
    }
    private static Map<String,Object> invoke(PlanetChildVault.LocalV2AppOwner owner,String method,Map<String,Object> request) throws Exception {return new Pending(owner,method,request).joined();}
    private static PlanetChildVault.LocalV2AppOwner owner(ActivityScenario<MainActivity> scenario) throws Exception {AtomicReference<PlanetChildVault.LocalV2AppOwner> actual=new AtomicReference<>();scenario.onActivity(activity->{try{actual.set((PlanetChildVault.LocalV2AppOwner)field(activity.getBridge().getPlugin("PlanetChild").getInstance(),"owner"));}catch(Exception failure){throw new AssertionError(failure);}});assertNotNull(actual.get());return actual.get();}
    @Test public void nativeJourneyAuthorityAndFreshNodeAdmissionRemainRequired() throws Exception {
        for(Constructor<?> ctor:PlanetChildVault.LocalV2JourneyProgressPermit.class.getDeclaredConstructors())assertTrue(Modifier.isPrivate(ctor.getModifiers()));for(Method method:PlanetChildVault.LocalV2JourneyProgressPermit.class.getDeclaredMethods())if(Modifier.isStatic(method.getModifiers()))assertTrue(Modifier.isPrivate(method.getModifiers()));
        Assume.assumeTrue("Genuine approved fixture tested separately",!args.getString("literaryChildJourneyFixtureAvailable","").equals("true"));
        try(ActivityScenario<MainActivity> scenario=ActivityScenario.launch(MainActivity.class)){PlanetChildVault.LocalV2AppOwner actual=owner(scenario);for(String method:Arrays.asList("listJourneys","readJourneyProgress","openJourney","advanceJourney")){Map<String,Object> request=base("2".repeat(32));if(method.equals("openJourney")||method.equals("advanceJourney")){request.put("journeyId","fixture-journey");request.put("expectedRevision",0L);}if(method.equals("advanceJourney")){request.put("currentNodeId","fixture-node");request.put("action","complete");}assertNotEquals("Caller token cannot authorize", "ok",invoke(actual,method,request).get("status"));}}
    }
    private Map<String,Object> fixture() throws Exception {try(InputStream input=InstrumentationRegistry.getInstrumentation().getContext().getAssets().open("child-journey-runtime-fixture-v1.json")){byte[] buffer=new byte[65536];int used=0;try{while(used<buffer.length){int n=input.read(buffer,used,buffer.length-used);if(n<0)break;assertTrue(n>0);used+=n;}assertTrue(used>0);assertEquals(-1,input.read());Map<String,Object> value=PlanetChildDataTransport.ownV2DTO(new org.json.JSONObject(new String(buffer,0,used,StandardCharsets.UTF_8)));assertEquals(new HashSet<>(Arrays.asList("journeyId","profileId","locale")),value.keySet());PlanetChildJourney.identifier((String)value.get("journeyId"));PlanetChildJourney.identifier((String)value.get("profileId"));assertTrue(Arrays.asList("ru","en").contains(value.get("locale")));return value;}finally{Arrays.fill(buffer,(byte)0);}}}
    private org.json.JSONObject preparedAsset(String fixed,int bound) throws Exception {try(InputStream input=context.getAssets().open("public/"+fixed)){byte[] buffer=new byte[bound];int used=0;try{while(used<bound){int n=input.read(buffer,used,bound-used);if(n<0)break;if(n<=0)throw new IllegalStateException();used+=n;}if(used<=0||input.read()!=-1)throw new IllegalStateException();return new org.json.JSONObject(new String(buffer,0,used,StandardCharsets.UTF_8));}finally{Arrays.fill(buffer,(byte)0);}}}
    private boolean counterpartPrepared(String locale) {try{org.json.JSONArray packages=preparedAsset("child-native/catalog-v1.json",65536).getJSONArray("packages");if(packages.length()>32)return false;for(int i=0;i<packages.length();i++){String hash=packages.getJSONObject(i).getString("packageChecksum");if(!hash.matches("[a-f0-9]{64}"))return false;org.json.JSONObject candidate=preparedAsset("child-native/packages/"+hash+".json",8388608);if(locale.equals(candidate.getString("locale")))return true;}return false;}catch(Exception unavailable){return false;}}
    @Test public void genuineJourneyContinueKeepsProgressAcrossRestartAndAllowedLocale() throws Exception {
        Assume.assumeTrue("NOT_RUN: original private approved native journey pins required",args.getString("literaryChildJourneyFixtureAvailable","").equals("true"));Map<String,Object> fixture=fixture();
        try(ActivityScenario<MainActivity> scenario=ActivityScenario.launch(MainActivity.class)){PlanetChildVault.LocalV2AppOwner actual=owner(scenario);Object existing=field(actual,"context");Map<String,Object> boot=existing==null?invoke(actual,"bootstrap",map("version",2L,"requestId",id())):invoke(actual,"readContext",base((String)field(existing,"token")));assertEquals("child",boot.get("status"));Map<String,Object> nativeContext=row(boot.get("context"));assertEquals(fixture.get("profileId"),nativeContext.get("profileId"));assertEquals(fixture.get("locale"),nativeContext.get("locale"));String token=(String)nativeContext.get("token");Map<String,Object> saved=data(invoke(actual,"readJourneyProgress",base(token)));Map<String,Object> open=base(token);open.put("journeyId",fixture.get("journeyId"));open.put("expectedRevision",revision(saved.get("revision")));Map<String,Object> journey=data(invoke(actual,"openJourney",open));assertTrue(Arrays.asList("opened","restored").contains(journey.get("status")));Map<String,Object> progress=row(journey.get("progress"));
            Map<String,Object> restart=base(token);restart.put("journeyId",fixture.get("journeyId"));restart.put("currentNodeId",progress.get("currentNodeId"));restart.put("expectedRevision",revision(journey.get("revision")));restart.put("action","restart");Map<String,Object> restarted=data(invoke(actual,"advanceJourney",restart));assertEquals(revision(journey.get("revision"))+1,revision(restarted.get("revision")));assertEquals(progress.get("completedNodeIds"),row(restarted.get("progress")).get("completedNodeIds"));assertNotNull(restarted.get("node"));Map<String,Object> nextProgress=row(restarted.get("progress"));String current=(String)nextProgress.get("currentNodeId");assertEquals(current,row(row(restarted.get("node")).get("reference")).get("id"));
            Map<String,Object> complete=base(token);complete.put("journeyId",fixture.get("journeyId"));complete.put("currentNodeId",current);complete.put("expectedRevision",revision(restarted.get("revision")));complete.put("action","complete");Map<String,Object> advanced=data(invoke(actual,"advanceJourney",complete));assertEquals(revision(restarted.get("revision"))+1,revision(advanced.get("revision")));assertTrue(((List<?>)row(advanced.get("progress")).get("completedNodeIds")).contains(current));assertEquals("retired",data(invoke(actual,"closeJourney",base(token))).get("status"));
            Map<String,Object> reopen=base(token);reopen.put("journeyId",fixture.get("journeyId"));reopen.put("expectedRevision",revision(advanced.get("revision")));Map<String,Object> resumed=data(invoke(actual,"openJourney",reopen));assertEquals("restored",resumed.get("status"));assertEquals(row(advanced.get("progress")).get("completedNodeIds"),row(resumed.get("progress")).get("completedNodeIds"));
            assertEquals("retired",invoke(actual,"retire",base(token)).get("status"));Map<String,Object> fresh=invoke(actual,"bootstrap",map("version",2L,"requestId",id()));assertEquals("child",fresh.get("status"));Map<String,Object> nextContext=row(fresh.get("context"));assertEquals(fixture.get("profileId"),nextContext.get("profileId"));String nextToken=(String)nextContext.get("token");assertNotEquals(token,nextToken);Map<String,Object> protectedReread=data(invoke(actual,"readJourneyProgress",base(nextToken)));assertEquals(resumed.get("revision"),protectedReread.get("revision"));assertEquals(row(resumed.get("progress")).get("completedNodeIds"),row(protectedReread.get("progress")).get("completedNodeIds"));Map<String,Object> freshOpen=base(nextToken);freshOpen.put("journeyId",fixture.get("journeyId"));freshOpen.put("expectedRevision",revision(protectedReread.get("revision")));Map<String,Object> restored=data(invoke(actual,"openJourney",freshOpen));assertEquals("restored",restored.get("status"));
            Assume.assumeTrue("NOT_RUN: counterpart reviewed locale package and genuine PIN/OS UI operator prerequisites required",args.getString("literaryChildJourneyLocaleGateFixtureAvailable","").equals("true"));String other="ru".equals(nextContext.get("locale"))?"en":"ru";Assume.assumeTrue("NOT_RUN: no counterpart package prepared; native profile mutation not dispatched",counterpartPrepared(other));Map<String,Object> locale=base(nextToken);locale.put("action","expand-access-settings");locale.put("target",map("profileId",fixture.get("profileId"),"changes",map("locale",other)));
            // This invokes the existing genuine native Parent Gate. The fixture
            // never clicks its native control, types a PIN or grants an OS proof.
            Map<String,Object> localized=new Pending(actual,"perform",locale).joined(60);Assume.assumeTrue("NOT_RUN: counterpart locale package must really admit the current child", "child".equals(localized.get("status")));Map<String,Object> localContext=row(localized.get("context"));assertEquals(other,localContext.get("locale"));assertEquals(fixture.get("profileId"),localContext.get("profileId"));String localToken=(String)localContext.get("token");assertNotEquals(nextToken,localToken);Map<String,Object> localProgress=data(invoke(actual,"readJourneyProgress",base(localToken)));assertEquals(row(restored.get("progress")).get("completedNodeIds"),row(localProgress.get("progress")).get("completedNodeIds"));Map<String,Object> localOpen=base(localToken);localOpen.put("journeyId",fixture.get("journeyId"));localOpen.put("expectedRevision",revision(localProgress.get("revision")));Map<String,Object> localRoute=data(invoke(actual,"openJourney",localOpen));assertEquals("restored",localRoute.get("status"));assertEquals(row(restored.get("progress")).get("completedNodeIds"),row(localRoute.get("progress")).get("completedNodeIds"));
        }
    }
    // AUTHORED_NOT_RUN: pure typed transition/storage/codec fixtures, never CHILD/PIN admission.
    @Test public void childLocalePureTransitionRequiresExplicitParentPolicyAndPreservesPinAndSibling() throws Exception {
        for(String name:Arrays.asList("valid","locked","legacy","missing-policy","current-only","wrong-profile","wrong-revision","no-op"))assertTrue(name,PlanetChildVault.fixtureChildLocaleTransition(context,name));
    }
    @Test public void canonicalReadingLedgerRetainsLegacySiblingAndUnknownAnchorWithoutCapacityLoss() throws Exception {
        for(String name:Arrays.asList("legacy","codec","migration","history","profile","downloads","capacity","unknown-anchor"))assertTrue(name,PlanetChildDataStore.fixtureReadingScenario(context,name));
    }
    @Test public void signedReadingAnchorsAndPrivateWireRefuseAliasesCapabilitiesAndMalformedCas() throws Exception {
        PlanetChildReadingPosition.Record record=new PlanetChildReadingPosition.Record("work","Work.ONE",1,"Passage.ONE");assertEquals("Work.ONE",PlanetChildReadingPosition.decode(record.dto()).id);
        Map<String,Object> reference=map("kind","work","id","Work.ONE","contentChecksum","a".repeat(64)),anchors=map("schemaVersion",1L,"anchorVersion",1L,"segments",Arrays.asList(map("anchorId","Passage.ONE","text","One")),"narration",null);
        PlanetChildReadingPosition.membership(record,reference,anchors,"One");Map<String,Object> wrongVersion=new LinkedHashMap<>(record.dto());wrongVersion.put("schemaVersion",true);denied(()->PlanetChildReadingPosition.decode(wrongVersion));Map<String,Object> extra=new LinkedHashMap<>(record.dto());extra.put("locale","ru");denied(()->PlanetChildReadingPosition.decode(extra));
        Map<String,Object> duplicate=new LinkedHashMap<>(anchors);duplicate.put("segments",Arrays.asList(map("anchorId","Passage.ONE","text","O"),map("anchorId","Passage.ONE","text","ne")));denied(()->PlanetChildReadingPosition.anchors(duplicate,"One"));PlanetChildReadingPosition.Record unknown=new PlanetChildReadingPosition.Record("work","Work.ONE",2,"Passage.ONE");denied(()->PlanetChildReadingPosition.membership(unknown,reference,anchors,"One"));
        Map<String,Object> cueGap=new LinkedHashMap<>(anchors);cueGap.put("narration",map("assetId","Audio.ONE","sha256","a".repeat(64),"sampleRate",8000L,"frameCount",8000L,"cues",Arrays.asList(map("anchorId","Passage.ONE","startFrame",1L,"endFrame",8000L))));denied(()->PlanetChildReadingPosition.anchors(cueGap,"One"));
        Map<String,Object> write=base("2".repeat(32));write.put("reference",reference);write.put("expectedRevision",0L);write.put("position",record.dto());assertEquals(record,PlanetChildDataTransport.decodeV2("rememberReadingPosition",write).readingPosition);
        for(String key:Arrays.asList("profileId","approved","url","locale","anchorMap")){Map<String,Object> untrusted=new LinkedHashMap<>(write);untrusted.put(key,true);denied(()->PlanetChildDataTransport.decodeV2("rememberReadingPosition",untrusted));}for(Object invalid:Arrays.asList(true,-1L,0.5d,9007199254740990L)){Map<String,Object> bad=new LinkedHashMap<>(write);bad.put("expectedRevision",invalid);denied(()->PlanetChildDataTransport.decodeV2("rememberReadingPosition",bad));}
    }
}
