package ru.probpera.literaryplanet;

import android.content.Context;
import android.os.Bundle;
import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;
import java.nio.charset.StandardCharsets;
import java.util.*;
import org.json.JSONObject;
import org.junit.*;
import org.junit.runner.RunWith;
import static org.junit.Assert.*;

/** Synthetic byte/storage regressions; execution belongs to the whole review.
 * cannot supply genuine review, consent, rights, private media permits or
 * installed lifecycle acceptance. No production source pins are changed. */
@RunWith(AndroidJUnit4.class)
public final class PlanetChildRouteMediaDownloadsRuntimeTest {
    private final Context context=InstrumentationRegistry.getInstrumentation().getTargetContext();
    private final Bundle args=InstrumentationRegistry.getArguments();
    @Before public void ownRun(){assertEquals("local-v2-child-route-media-downloads",args.getString("literaryChildRouteMediaPhase"));assertTrue(args.getString("literaryRunId","").matches("[a-f0-9]{32}"));}
    private interface Work {void run()throws Exception;}
    private static void denied(Work work)throws Exception {boolean refused=false;try{work.run();}catch(Exception unavailable){refused=true;}assertTrue("Closed refusal required",refused);}
    private byte[] bytes(String locale,String scenario)throws Exception{return PlanetChildVault.fixturePassportMediaRouteBytes(context,"journey-one",locale,scenario);}
    private static PlanetChildPassport.Route route(String id,String locale,byte[] bytes)throws Exception {String hash="a".repeat(64);return new PlanetChildPassport.Route(id,2,2,"fixture-package",2,hash,hash,"fixture-policy",hash,locale,7,"android-google","RU",bytes);}
    private static Map<String,Object> row(Object... fields){Map<String,Object> value=new LinkedHashMap<>();for(int i=0;i<fields.length;i+=2)value.put((String)fields[i],fields[i+1]);return value;}
    @SuppressWarnings("unchecked") private static Map<String,Object> parse(byte[] bytes)throws Exception {java.lang.reflect.Method method=Class.forName("ru.probpera.literaryplanet.PlanetChildVault$LocalV2PackageJson").getDeclaredMethod("read",byte[].class,int.class);method.setAccessible(true);return(Map<String,Object>)method.invoke(null,bytes,PlanetChildPassport.MAX_ROUTE_BYTES);}
    private static byte[] canonical(Object value)throws Exception {java.lang.reflect.Method method=Class.forName("ru.probpera.literaryplanet.PlanetChildVault$LocalV2PackageJson").getDeclaredMethod("bytes",Object.class,boolean.class);method.setAccessible(true);return(byte[])method.invoke(null,value,true);}
    @SuppressWarnings("unchecked") private static Map<String,Object> media(Map<String,Object> snapshot){return(Map<String,Object>)((List<?>)snapshot.get("media")).get(0);}
    private static String sha(byte[] bytes)throws Exception {byte[] digest=java.security.MessageDigest.getInstance("SHA-256").digest(bytes);StringBuilder result=new StringBuilder();for(byte b:digest)result.append(String.format(Locale.ROOT,"%02x",b&255));return result.toString();}
    private static byte[] chunk(String name,byte[] bytes)throws Exception {java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();byte[] kind=name.getBytes(StandardCharsets.US_ASCII);out.write(java.nio.ByteBuffer.allocate(4).putInt(bytes.length).array());out.write(kind);out.write(bytes);java.util.zip.CRC32 crc=new java.util.zip.CRC32();crc.update(kind);crc.update(bytes);out.write(java.nio.ByteBuffer.allocate(4).putInt((int)crc.getValue()).array());return out.toByteArray();}
    private static byte[] staticPng()throws Exception {java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream(),compressed=new java.io.ByteArrayOutputStream();out.write(new byte[]{(byte)137,80,78,71,13,10,26,10});out.write(chunk("IHDR",java.nio.ByteBuffer.allocate(13).putInt(1).putInt(1).put(new byte[]{8,6,0,0,0}).array()));try(java.util.zip.DeflaterOutputStream zip=new java.util.zip.DeflaterOutputStream(compressed)){zip.write(new byte[]{0,0,0,0,0});}out.write(chunk("IDAT",compressed.toByteArray()));out.write(chunk("IEND",new byte[0]));return out.toByteArray();}
    @Test public void exactNarrationAndRawProvenanceRemainInsideCanonicalSavedBytes()throws Exception {byte[] raw=bytes("en","valid");try{assertEquals("journey-one",PlanetChildVault.validatePassportRouteSnapshot(raw));JSONObject snapshot=new JSONObject(new String(raw,StandardCharsets.UTF_8)),media=snapshot.getJSONArray("media").getJSONObject(0);assertEquals(2,snapshot.getInt("schemaVersion"));byte[] wav=android.util.Base64.decode(media.getString("encodedBase64"),android.util.Base64.NO_WRAP),quality=android.util.Base64.decode(media.getString("audioProvenanceBase64"),android.util.Base64.NO_WRAP);try{assertEquals(204,wav.length);assertEquals(160,PlanetChildMedia.preflight(wav,"audio/wav").length);JSONObject source=new JSONObject(new String(quality,StandardCharsets.UTF_8));assertEquals("en",source.getString("locale"));assertEquals("fixture-licensor",source.getString("licensorId"));assertEquals("same-locale-text",source.getString("reducedAudioFallback"));assertEquals(media.getJSONObject("payload").getString("scriptChecksum"),source.getString("scriptChecksum"));assertEquals("Synthetic English narration transcript.",media.getJSONObject("payload").getString("transcript"));}finally{Arrays.fill(wav,(byte)0);Arrays.fill(quality,(byte)0);}}finally{Arrays.fill(raw,(byte)0);}}
    @Test public void savedCodecDetachesExactBinaryTranscriptAndEvidenceBytes()throws Exception {byte[] raw=bytes("ru","valid");PlanetChildPassport.Route original=route("journey-one","ru",raw);PlanetChildPassport.Ledger saved=PlanetChildPassport.empty().saved(original),restored=null;byte[] encoded=saved.encode();try{restored=PlanetChildPassport.decode(encoded);assertEquals(saved,restored);saved.wipe();assertArrayEquals(raw,restored.routes.get(0).copy());}finally{if(restored!=null)restored.wipe();saved.wipe();Arrays.fill(raw,(byte)0);Arrays.fill(encoded,(byte)0);}}
    @Test public void localeSpecificDownloadsDoNotReplaceSiblingLocaleBytes()throws Exception {byte[] ru=bytes("ru","valid"),en=bytes("en","valid");PlanetChildPassport.Ledger saved=PlanetChildPassport.empty().saved(route("journey-one","ru",ru)).saved(route("journey-one","en",en));try{assertEquals(2,saved.routes.size());assertArrayEquals(ru,saved.routes.get(0).copy());assertArrayEquals(en,saved.routes.get(1).copy());PlanetChildPassport.Ledger renewed=saved.saved(route("journey-one","ru",ru));try{assertEquals(2,renewed.routes.size());assertSame(saved.routes.get(1),renewed.routes.get(1));assertArrayEquals(en,renewed.routes.get(1).copy());}finally{renewed.routes.get(0).wipe();}}finally{saved.wipe();Arrays.fill(ru,(byte)0);Arrays.fill(en,(byte)0);}}
    @Test public void wrongSnapshotLocaleCannotEnterProtectedRouteCodec()throws Exception {byte[] raw=bytes("en","valid");try{denied(()->route("journey-one","ru",raw));denied(()->PlanetChildVault.passportRouteMediaSummary(raw,"ru"));}finally{Arrays.fill(raw,(byte)0);}}
    @Test public void explicitMediaSummaryCountsRealBytesAndTranscriptUtf8()throws Exception {for(String locale:Arrays.asList("ru","en")){byte[] raw=bytes(locale,"valid");try{Map<String,Object> summary=PlanetChildVault.passportRouteMediaSummary(raw,locale);String transcript="ru".equals(locale)?"Синтетический текст озвучки.":"Synthetic English narration transcript.";assertEquals(locale,summary.get("locale"));assertEquals("downloaded",summary.get("audioStatus"));assertEquals(1L,summary.get("audioItemCount"));assertEquals(0L,summary.get("imageItemCount"));assertEquals(204L,summary.get("mediaByteLength"));assertEquals((long)transcript.getBytes(StandardCharsets.UTF_8).length,summary.get("transcriptByteLength"));assertTrue(raw.length>204);}finally{Arrays.fill(raw,(byte)0);}}}
    @Test public void retainedTextOnlySchemaNeverInfersEnglishOrRussianAudio()throws Exception {byte[] raw=PlanetChildVault.fixturePassportRouteBytes(context,"journey-one");try{for(String locale:Arrays.asList("ru","en")){Map<String,Object> summary=PlanetChildVault.passportRouteMediaSummary(raw,locale);assertEquals("text-only",summary.get("audioStatus"));assertEquals(0L,summary.get("audioItemCount"));assertEquals(0L,summary.get("mediaByteLength"));assertEquals(0L,summary.get("transcriptByteLength"));}}finally{Arrays.fill(raw,(byte)0);}}
    @Test public void audioEvidenceMustMatchScriptPerformerLocaleAndHumanVoice()throws Exception {for(String scenario:Arrays.asList("missing-provenance","wrong-locale","wrong-script","wrong-performer","cloned-voice")){byte[] raw=bytes("en",scenario);try{denied(()->PlanetChildVault.validatePassportRouteSnapshot(raw));}finally{Arrays.fill(raw,(byte)0);}}}
    @Test public void actualPcmDurationMustMatchThePinnedQualityDocument()throws Exception {byte[] raw=bytes("ru","wrong-duration");try{denied(()->PlanetChildVault.validatePassportRouteSnapshot(raw));}finally{Arrays.fill(raw,(byte)0);}}
    @Test public void attachmentCannotEscapeTextClosureOrAddCallerUrlAuthority()throws Exception {for(String scenario:Arrays.asList("wrong-owner","unknown-field","duplicate")){byte[] raw=bytes("ru",scenario);try{denied(()->PlanetChildVault.validatePassportRouteSnapshot(raw));}finally{Arrays.fill(raw,(byte)0);}}}
    @Test public void binaryChecksumLengthAndCanonicalBase64AreAllRequired()throws Exception {for(String scenario:Arrays.asList("wrong-binary-hash","noncanonical-base64")){byte[] raw=bytes("en",scenario);try{denied(()->PlanetChildVault.validatePassportRouteSnapshot(raw));}finally{Arrays.fill(raw,(byte)0);}}byte[] valid=bytes("en","valid");try{String text=new String(valid,StandardCharsets.UTF_8);assertTrue(text.contains("\"bytes\":204"));denied(()->PlanetChildVault.validatePassportRouteSnapshot(text.replace("\"bytes\":204","\"bytes\":205").getBytes(StandardCharsets.UTF_8)));}finally{Arrays.fill(valid,(byte)0);}}
    @Test public void unsupportedVideoRemainsAnOpenDeny()throws Exception {byte[] raw=bytes("en","unsupported-video");try{denied(()->PlanetChildVault.validatePassportRouteSnapshot(raw));denied(()->PlanetChildMedia.preflight(new byte[]{1,2,3},"video/mp4"));}finally{Arrays.fill(raw,(byte)0);}}
    @Test public void routeCapacityCountsAllLocalesWithoutEviction()throws Exception {PlanetChildPassport.Ledger saved=PlanetChildPassport.empty();try{for(int i=0;i<16;i++)for(String locale:Arrays.asList("ru","en")){String id="route-"+i;byte[] raw=PlanetChildVault.fixturePassportMediaRouteBytes(context,id,locale,"valid");try{saved=saved.saved(route(id,locale,raw));}finally{Arrays.fill(raw,(byte)0);}}assertEquals(32,saved.routes.size());byte[] raw=PlanetChildVault.fixturePassportMediaRouteBytes(context,"overflow","en","valid");PlanetChildPassport.Route extra=route("overflow","en",raw);try{PlanetChildPassport.Ledger full=saved;denied(()->full.saved(extra));assertEquals(32,full.routes.size());}finally{extra.wipe();Arrays.fill(raw,(byte)0);}}finally{saved.wipe();}}
    @Test public void profileByteLimitIncludesBase64TextAndRawEvidenceWithoutEviction()throws Exception {PlanetChildPassport.Ledger saved=PlanetChildPassport.empty();try{for(int i=0;i<4;i++){String id="large-"+i;byte[] raw=PlanetChildVault.fixturePassportMediaRouteBytes(context,id,"en","large");try{assertTrue(raw.length<524288);assertTrue(raw.length>450000);saved=saved.saved(route(id,"en",raw));}finally{Arrays.fill(raw,(byte)0);}}byte[] raw=PlanetChildVault.fixturePassportMediaRouteBytes(context,"large-overflow","en","large");PlanetChildPassport.Route extra=route("large-overflow","en",raw);try{PlanetChildPassport.Ledger full=saved;denied(()->full.saved(extra));assertEquals(4,full.routes.size());}finally{extra.wipe();Arrays.fill(raw,(byte)0);}}finally{saved.wipe();}}
    @Test public void oversizedRouteFailsBeforeChangingProtectedLedger()throws Exception {byte[] raw=bytes("en","oversize");try{denied(()->PlanetChildVault.validatePassportRouteSnapshot(raw));denied(()->route("journey-one","en",raw));}finally{Arrays.fill(raw,(byte)0);}}
    @Test public void saveWireRetainsExpectedRevisionAndRejectsCallerMediaAndConsent()throws Exception {Map<String,Object> request=row("version",2L,"requestId","1".repeat(32),"contextToken","2".repeat(32),"journeyId","journey-one","expectedRevision",7L);assertEquals(7,PlanetChildDataTransport.decodeV2("saveJourneyRoute",request).expectedRevision);for(String field:Arrays.asList("media","encodedBase64","audioProvenanceBase64","approved","soundEnabled","narrationEnabled","locale","profileId")){Map<String,Object> extra=new LinkedHashMap<>(request);extra.put(field,true);denied(()->PlanetChildDataTransport.decodeV2("saveJourneyRoute",extra));}}
    @Test public void scalarBytesNeverConstructAGenuinePrivatePlaybackPermit()throws Exception {byte[] raw=bytes("en","valid");try{assertTrue(PlanetChildVault.fixturePassportPinsDeny(context));denied(()->PlanetChildMedia.Owner.decode(null,raw));}finally{Arrays.fill(raw,(byte)0);}}
    @Test public void parentDownloadsWipeOnlyTargetRouteMediaAndKeepSiblingFacts()throws Exception {assertTrue(PlanetChildDataStore.fixturePassportMediaScenario(context,"downloads"));assertTrue(PlanetChildVault.fixtureCanonicalDeletion(context,"downloads"));}
    @Test public void parentHistoryAndProfileRemoveTargetMediaAndKeepSiblingBytes()throws Exception {for(String scenario:Arrays.asList("history","profile"))assertTrue(PlanetChildDataStore.fixturePassportMediaScenario(context,scenario));}
    @Test public void detachedEncryptedMediaSurvivesOwnerCloseAndCorruptionStaysClosed()throws Exception {assertTrue(PlanetChildDataStore.fixturePassportMediaScenario(context,"codec"));assertTrue(PlanetChildDataStore.fixturePassportMediaScenario(context,"corrupt"));}
    @Test public void encryptedMediaRestartPreservesExactBytesAndPendingDebtDenies()throws Exception {String run=args.getString("literaryRunId");for(String phase:Arrays.asList("write","read","pending","pending-reopen"))assertTrue(PlanetChildDataStore.fixturePassportMediaPersistence(context,run,phase));}
    @Test public void largeNarrationAcceptsCanonicalBase64WithoutRecursiveMatcher()throws Exception {
        byte[] raw=bytes("en","large");PlanetChildPassport.Ledger saved=null,restored=null;byte[] encoded=null;
        try{assertEquals("journey-one",PlanetChildVault.validatePassportRouteSnapshot(raw));assertEquals(360044L,PlanetChildVault.passportRouteMediaSummary(raw,"en").get("mediaByteLength"));saved=PlanetChildPassport.empty().saved(route("journey-one","en",raw));encoded=saved.encode();restored=PlanetChildPassport.decode(encoded);saved.wipe();assertArrayEquals(raw,restored.routes.get(0).copy());}
        finally{if(saved!=null)saved.wipe();if(restored!=null)restored.wipe();if(encoded!=null)Arrays.fill(encoded,(byte)0);Arrays.fill(raw,(byte)0);}
    }
    @SuppressWarnings("unchecked") @Test public void largeRawNarrationEvidencePreservesSourceWhitespaceAndExactChecksum()throws Exception {
        byte[] raw=bytes("en","valid"),quality=null,extended=null,payloadBytes=null,saved=null;
        try{Map<String,Object> snapshot=parse(raw),asset=media(snapshot),payload=(Map<String,Object>)asset.get("payload");quality=android.util.Base64.decode((String)asset.get("audioProvenanceBase64"),android.util.Base64.NO_WRAP);Map<String,Object> evidence=parse(quality);evidence.put("loudnessReport","x".repeat(8192));evidence.put("qualityReport","y".repeat(8192));byte[] canonicalEvidence=canonical(evidence);try{extended=new byte[canonicalEvidence.length+2];extended[0]=' ';System.arraycopy(canonicalEvidence,0,extended,1,canonicalEvidence.length);extended[extended.length-1]='\n';}finally{Arrays.fill(canonicalEvidence,(byte)0);}payload.put("qualityChecksum",sha(extended));payloadBytes=canonical(payload);((Map<String,Object>)asset.get("entity")).put("contentChecksum",sha(payloadBytes));asset.put("audioProvenanceBase64",android.util.Base64.encodeToString(extended,android.util.Base64.NO_WRAP));saved=canonical(snapshot);assertEquals("journey-one",PlanetChildVault.validatePassportRouteSnapshot(saved));assertArrayEquals(extended,android.util.Base64.decode((String)media(parse(saved)).get("audioProvenanceBase64"),android.util.Base64.NO_WRAP));}
        finally{for(byte[] b:new byte[][]{raw,quality,extended,payloadBytes,saved})if(b!=null)Arrays.fill(b,(byte)0);}
    }
    @Test public void savedBase64RejectsMisplacedPaddingWhitespaceAndNonzeroPadBits()throws Exception {
        byte[] raw=bytes("en","valid");try{Map<String,Object> snapshot=parse(raw),asset=media(snapshot);String valid=(String)asset.get("encodedBase64");for(String bad:Arrays.asList("A","AA=","AA===","A=AA","====","AA-A",valid+"\n",valid.substring(0,valid.length()-4)+"AAAB=")){asset.put("encodedBase64",bad);byte[] changed=canonical(snapshot);try{denied(()->PlanetChildVault.validatePassportRouteSnapshot(changed));}finally{Arrays.fill(changed,(byte)0);}}asset.put("encodedBase64",valid);java.lang.reflect.Method decode=Class.forName("ru.probpera.literaryplanet.PlanetChildVault$LocalV2NarrationProvenance").getDeclaredMethod("decodeCanonical",String.class,int.class);decode.setAccessible(true);for(String bad:Arrays.asList("AB==","AAB="))denied(()->decode.invoke(null,bad,4));byte[] one=(byte[])decode.invoke(null,"AA==",1),two=(byte[])decode.invoke(null,"AAA=",2);try{assertEquals(1,one.length);assertEquals(2,two.length);denied(()->decode.invoke(null,"AAA=",1));}finally{Arrays.fill(one,(byte)0);Arrays.fill(two,(byte)0);}}
        finally{Arrays.fill(raw,(byte)0);}
    }
    @Test public void schemaTwoEnglishTextOnlyRetainsTextWithoutRussianSpeech()throws Exception {
        byte[] raw=bytes("en","valid"),saved=null;PlanetChildPassport.Route route=null;
        try{Map<String,Object> snapshot=parse(raw);Object originalText=snapshot.get("nodes");snapshot.put("media",Collections.emptyList());saved=canonical(snapshot);route=route("journey-one","en",saved);assertEquals(originalText,parse(route.copy()).get("nodes"));Map<String,Object> summary=PlanetChildVault.passportRouteMediaSummary(saved,"en");assertEquals("en",summary.get("locale"));assertEquals("text-only",summary.get("audioStatus"));assertEquals(0L,summary.get("audioItemCount"));assertEquals(0L,summary.get("transcriptByteLength"));assertEquals(0L,summary.get("mediaByteLength"));}
        finally{if(route!=null)route.wipe();Arrays.fill(raw,(byte)0);if(saved!=null)Arrays.fill(saved,(byte)0);}
    }
    @SuppressWarnings("unchecked") @Test public void staticImageDownloadStoresExactBytesWithoutInferringNarration()throws Exception {
        byte[] raw=bytes("en","valid"),png=staticPng(),payloadBytes=null,saved=null,copy=null;PlanetChildPassport.Route route=null;
        try{Map<String,Object> snapshot=parse(raw),asset=media(snapshot),payload=row("role","image","altText","Synthetic static illustration","transcript",null,"scriptId",null,"scriptChecksum",null,"performerId",null,"qualityChecksum",null);payloadBytes=canonical(payload);asset.put("assetId","fixture-image");asset.put("entity",row("kind","image","id","fixture-image","contentChecksum",sha(payloadBytes)));asset.put("payload",payload);asset.put("policy",row("kind","image","id","fixture-image"));asset.put("inventoryKey","fixture-image.png");asset.put("sha256",sha(png));asset.put("bytes",(long)png.length);asset.put("mime","image/png");asset.put("encodedBase64",android.util.Base64.encodeToString(png,android.util.Base64.NO_WRAP));asset.put("audioProvenanceBase64",null);saved=canonical(snapshot);route=route("journey-one","en",saved);copy=route.copy();assertArrayEquals(saved,copy);assertEquals(1,PlanetChildMedia.preflight(png,"image/png").width);Map<String,Object> summary=PlanetChildVault.passportRouteMediaSummary(saved,"en");assertEquals("text-only",summary.get("audioStatus"));assertEquals(0L,summary.get("audioItemCount"));assertEquals(1L,summary.get("imageItemCount"));assertEquals((long)png.length,summary.get("mediaByteLength"));asset.put("audioProvenanceBase64","AA==");byte[] wrong=canonical(snapshot);try{denied(()->PlanetChildVault.validatePassportRouteSnapshot(wrong));}finally{Arrays.fill(wrong,(byte)0);}}
        finally{if(route!=null)route.wipe();for(byte[] b:new byte[][]{raw,png,payloadBytes,saved,copy})if(b!=null)Arrays.fill(b,(byte)0);}
    }
}
