version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "04:17"
      timezone: Etc/UTC
    open-pull-requests-limit: 8
    rebase-strategy: auto
    versioning-strategy: increase
    groups:
      production-minor-and-patch:
        dependency-type: production
        update-types:
          - minor
          - patch
        patterns:
          - "*"
      development-minor-and-patch:
        dependency-type: development
        update-types:
          - minor
          - patch
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: weekly
      day: monday
      time: "04:37"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    rebase-strategy: auto
    groups:
      actions-minor-and-patch:
        update-types:
          - minor
          - patch
        patterns:
          - "*"
