// Generated by scripts/export-published-content.mjs. Do not edit by hand.
// Verified CMS withdrawals that suppress retired static article fallbacks.
export const cmsWithdrawnLegacyArticles = [] as const;
