// Generated by scripts/export-published-content.mjs. Do not edit by hand.
// Verified CMS withdrawals that suppress retired static article fallbacks.
export const cmsWithdrawnLegacyArticles = [
  {
    "cmsId": "cms-7ad1ab89-8a77-407d-b59a-6147c0e2a7a6",
    "canonicalPath": "/stati/mnenie-o-knige/mnenie-o-knige-devida-mitchella-pod-znakom-chernogo-lebedya",
    "legacyId": "page--article--page--books--14",
    "legacyPath": "/read/page-article/page-books/14"
  }
] as const;
