/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=scripts/wrangler.literary-news.jsonc --include-runtime=false scripts/workers/literary-news-worker-env.d.ts` (hash: 43e90a40d8026cea00d9ebb5bdcd678d)
interface __BaseEnv_Env {
	NEWS_STATE: KVNamespace;
	NEWS_RELEASE_SHA: "local";
	NEWS_PUBLIC_READER: DurableObjectNamespace<import("./literary-news-worker").LiteraryNewsPublicReader>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./literary-news-worker");
		durableNamespaces: "LiteraryNewsPublicReader";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEWS_RELEASE_SHA">> {}
}
