/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=scripts/wrangler.literary-news.jsonc --include-runtime=false scripts/workers/literary-news-worker-env.d.ts` (hash: 0f84cb441e01e96819b03740eb0c053b)
interface __BaseEnv_Env {
	NEWS_STATE: KVNamespace;
	NEWS_RELEASE_SHA: "local";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEWS_RELEASE_SHA">> {}
}
