/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=scripts/wrangler.writer-biography-english.jsonc --include-runtime=false --env-interface=WriterBiographyEnglishWorkerEnv scripts/workers/writer-biography-english-worker-env.d.ts` (hash: 690e0ee3d8599efed597f2d34f744cd7)
interface __BaseEnv_WriterBiographyEnglishWorkerEnv {
	AI: Ai;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./writer-biography-english-translation-worker");
	}
	interface Env extends __BaseEnv_WriterBiographyEnglishWorkerEnv {}
}
interface WriterBiographyEnglishWorkerEnv extends __BaseEnv_WriterBiographyEnglishWorkerEnv {}
