export const sandboxPaymentCopy = {
  reviewStatus: "draft-requires-editorial-review",
  ru: {
    title: "Тестовая покупка", intro: "Песочница YooKassa. Это тестовый платёж, реального списания нет.",
    amount: "Тестовая сумма", purchase: "Начать тестовую покупку", confirmation: "Продолжить тестовый платёж",
    check: "Проверить платёж", restore: "Найти тестовую покупку", retry: "Повторить с тем же запросом",
    busy: "Проверяем платёж…", uncertain: "Ответ пока не получен. Повторная попытка использует тот же запрос.",
    unavailable: "Сервис тестовых платежей недоступен. Попробуйте ещё раз.", authentication: "Войдите в аккаунт ещё раз.",
    denied: "Тестовые покупки для этого аккаунта недоступны.", empty: "Тестовых покупок для этого аккаунта пока нет.",
    catalogChanged: "Тестовая сумма изменилась. Проверьте новую сумму перед продолжением. Прежний запрос сохранён.",
    reviewPrice: "Проверить новую тестовую сумму", confirmPrice: "Продолжить с указанной тестовой суммой",
    priceReviewed: "Текущая сумма для следующего тестового платежа:", previousOrder: "Восстановлен прежний тестовый запрос с его исходной суммой.",
    previousAmount: "Прежняя тестовая сумма",
    new: "Запрос сохранён. Проверьте платёж или повторите с тем же запросом.",
    pending: "Тестовый платёж ожидает подтверждения.", waiting_for_capture: "Тестовый платёж ожидает завершения.",
    succeeded: "Тестовый платёж подтверждён. Для открытия приложения используйте кнопку восстановления доступа.",
    canceled: "Тестовый платёж отменён.", refunded: "Тестовый платёж возвращён. Доступ по этой покупке закрыт.",
    "refund-review-required": "Частичный возврат требует проверки. Новый доступ по этой покупке пока не выдаётся.",
    "reconcile-required": "Нужна сверка платежа с поддержкой. Новый платёж не создаётся.",
  },
  en: {
    title: "Sandbox purchase", intro: "YooKassa sandbox. This is a test payment; no real charge is made.",
    amount: "Test amount", purchase: "Start test purchase", confirmation: "Continue test payment",
    check: "Check payment", restore: "Find test purchase", retry: "Retry the same request",
    busy: "Checking payment…", uncertain: "No response yet. Retrying uses the same request.",
    unavailable: "Test payments are unavailable. Please try again.", authentication: "Please sign in to your account again.",
    denied: "Test purchases are unavailable for this account.", empty: "This account has no test purchases yet.",
    catalogChanged: "The test amount changed. Review the new amount before continuing. Your previous request is saved.",
    reviewPrice: "Review the new test amount", confirmPrice: "Continue with the displayed test amount",
    priceReviewed: "Current amount for the next test payment:", previousOrder: "Your previous test request was restored with its original amount.",
    previousAmount: "Previous test amount",
    new: "The request is saved. Check the payment or retry the same request.",
    pending: "The test payment is awaiting confirmation.", waiting_for_capture: "The test payment is awaiting completion.",
    succeeded: "The test payment is confirmed. Use Restore access to open the app.",
    canceled: "The test payment was canceled.", refunded: "The test payment was refunded. Access from this purchase is closed.",
    "refund-review-required": "The partial refund needs review. New access from this purchase is on hold.",
    "reconcile-required": "Please contact support to reconcile this payment. No new payment is created.",
  },
} as const;
