/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=AdminCloudflareBindings cloudflare-env.generated.d.ts` (hash: bba7c3aa133119bb2376f3a4d503a53c)
interface __BaseEnv_AdminCloudflareBindings {
	ADMIN_CATALOGS: R2Bucket;
	ASSETS: Fetcher;
	ADMIN_BASE_PATH: "/";
	NEXT_PUBLIC_ADMIN_URL: "https://admin.probpera.ru";
	NEXT_PUBLIC_SITE_URL: "https://probpera.ru";
	ADMIN_ALLOWED_ORIGINS: "admin.probpera.ru";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_AdminCloudflareBindings {}
}
interface AdminCloudflareBindings extends __BaseEnv_AdminCloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_BASE_PATH" | "NEXT_PUBLIC_ADMIN_URL" | "NEXT_PUBLIC_SITE_URL" | "ADMIN_ALLOWED_ORIGINS">> {}
}
