import {test} from 'node:test';import assert from 'node:assert/strict';import {validateRemoteAuthorization,validateCleanupObjects} from './remote-preflight.mjs';
const id='11111111-1111-4111-8111-111111111111',user='22222222-2222-4222-8222-222222222222';
const request={environment:'sandbox',endpoint:'https://synthetic.example/',projectId:'synthetic-only',runId:id,operations:['payment-sandbox'],testAccountIds:[user],schemaFingerprint:'a'.repeat(64),provider:'yookassa-sandbox',testMode:true,shopId:'123456',product:'sandbox.synthetic',catalogVersion:'fixture-1',amountMinor:101,currency:'RUB'};
const grant={...request,kind:'separate-owner-authorization',grantedBy:'owner',recordOnly:true,evidenceReference:'Synthetic test fixture; no real permission',notBefore:new Date(0).toISOString(),expiresAt:new Date(999999).toISOString()};
test('matching synthetic authorization remains offline and does not issue permission',()=>{const r=validateRemoteAuthorization(grant,request,1000);assert.equal(r.status,'PASS');assert.equal(r.networkRequests,0);assert.equal(r.mutations,0);assert.equal(r.productionActionsAuthorized,false);});
for(const [name,patch] of [['wrong endpoint',{endpoint:'https://other.example/'}],['wrong environment',{environment:'production'}],['unauthorized deletion',{operations:['deletion-fixtures']}],['wrong account',{testAccountIds:['33333333-3333-4333-8333-333333333333']}],['live mode',{testMode:false}],['wrong schema',{schemaFingerprint:'b'.repeat(64)}],['wrong run',{runId:'33333333-3333-4333-8333-333333333333'}]])test(name,()=>assert.equal(validateRemoteAuthorization(grant,{...request,...patch},1000).status,'BLOCKED_EXTERNAL'));
test('missing or expired permission denies',()=>{assert.equal(validateRemoteAuthorization(null,request,1000).status,'BLOCKED_EXTERNAL');assert.equal(validateRemoteAuthorization(grant,request,1000000).status,'BLOCKED_EXTERNAL');});
test('migration requires backup and exact reviewed hashes',()=>{const r={...request,operations:['migration-apply']};const g={...grant,operations:r.operations};assert.equal(validateRemoteAuthorization(g,r,1000).status,'BLOCKED_EXTERNAL');});
test('cleanup cannot use a broad prefix or another owner',()=>{const r={...request,operations:['cleanup-exact-objects']};const g={...grant,operations:r.operations,expiresAt:new Date(Date.now()+60000).toISOString()};for(const ledger of [[],[{kind:'profile',id:'prefix-*',ownerId:user,runId:id}],[{kind:'profile',id,ownerId:id,runId:id}]])assert.equal(validateCleanupObjects(g,r,ledger).status,'BLOCKED_EXTERNAL');});

test('same provider endpoint cannot substitute another test shop or price',()=>{for(const patch of[{shopId:'999999'},{amountMinor:102},{product:'sandbox.other'},{catalogVersion:'different'}])assert.equal(validateRemoteAuthorization(grant,{...request,...patch},1000).status,'BLOCKED_EXTERNAL');});
test('auth/deletion fixture operations require two exact ordinary users',()=>{for(const operation of['auth-fixtures','deletion-fixtures']){const r={...request,operations:[operation],testAccountIds:[]};const g={...grant,operations:[operation],testAccountIds:[]};assert.equal(validateRemoteAuthorization(g,r,1000).status,'BLOCKED_EXTERNAL');}});
