package ru.probpera.literaryplanet;

import java.io.*;
import java.util.*;

/** Protected semantic facts only. Saved IDs never admit current content. */
final class PlanetChildPassport {
    static final int MAX_IDS=2048,MAX_BYTES=8388608,MAX_AWARDS=256,MAX_ROUTES=32,MAX_ROUTE_BYTES=524288,MAX_ROUTE_TOTAL=2097152;
    private PlanetChildPassport() {}
    private static void require(boolean value) throws Exception {if(!value)throw new PlanetChildDataStore.Unavailable();}
    static final class Credit {
        final String journeyId,nodeId,kind,entityId;final long journeyVersion,contentVersion;
        Credit(String journey,String node,String kind,String entity,long journeyVersion,long contentVersion) throws Exception {
            journeyId=PlanetChildJourney.identifier(journey);nodeId=PlanetChildJourney.identifier(node);
            require(Arrays.asList("writer","work").contains(kind)&&journeyVersion>0&&journeyVersion<PlanetChildAppearance.MAX_SAFE&&contentVersion>0&&contentVersion<PlanetChildAppearance.MAX_SAFE);
            this.kind=kind;entityId=PlanetChildJourney.identifier(entity);this.journeyVersion=journeyVersion;this.contentVersion=contentVersion;
        }
        String key(){return journeyId+"\n"+journeyVersion+"\n"+contentVersion+"\n"+nodeId;}
        @Override public boolean equals(Object raw){if(!(raw instanceof Credit))return false;Credit c=(Credit)raw;return key().equals(c.key())&&kind.equals(c.kind)&&entityId.equals(c.entityId)&&journeyVersion==c.journeyVersion&&contentVersion==c.contentVersion;}
        @Override public int hashCode(){return Objects.hash(key(),kind,entityId,journeyVersion,contentVersion);}
    }

    static final class CompletedJourney {
        final String journeyId;final long journeyVersion,contentVersion;final List<String> nodeIds;
        CompletedJourney(String id,long journeyVersion,long contentVersion,List<String> nodes)throws Exception {
            journeyId=PlanetChildJourney.identifier(id);require(journeyVersion>0&&journeyVersion<PlanetChildAppearance.MAX_SAFE&&contentVersion>0&&contentVersion<PlanetChildAppearance.MAX_SAFE);PlanetChildJourney.validateNodes(id,nodes);this.journeyVersion=journeyVersion;this.contentVersion=contentVersion;nodeIds=Collections.unmodifiableList(new ArrayList<>(nodes));
        }
        String key(){return journeyId+"\n"+journeyVersion+"\n"+contentVersion;}
        @Override public boolean equals(Object raw){if(!(raw instanceof CompletedJourney))return false;CompletedJourney j=(CompletedJourney)raw;return journeyId.equals(j.journeyId)&&journeyVersion==j.journeyVersion&&contentVersion==j.contentVersion&&nodeIds.equals(j.nodeIds);}
        @Override public int hashCode(){return Objects.hash(journeyId,journeyVersion,contentVersion,nodeIds);}
    }

    /** Immutable versioned native award receipt, never a currency or permission. */
    static final class Award {
        final String programId,programChecksum,reviewChecksum,badgeId,journeyId,trigger;final long programVersion,ruleVersion,journeyVersion,contentVersion;final List<String> nodeIds;
        Award(String programId,long programVersion,String programChecksum,String reviewChecksum,String badgeId,long ruleVersion,String journeyId,long journeyVersion,long contentVersion,String trigger,List<String> nodeIds)throws Exception {
            this.programId=PlanetChildJourney.identifier(programId);this.programVersion=version(programVersion);this.programChecksum=hash(programChecksum);this.reviewChecksum=hash(reviewChecksum);this.badgeId=PlanetChildJourney.identifier(badgeId);this.ruleVersion=version(ruleVersion);this.journeyId=PlanetChildJourney.identifier(journeyId);this.journeyVersion=version(journeyVersion);this.contentVersion=version(contentVersion);require(Arrays.asList("completed-journey","completed-learning").contains(trigger));this.trigger=trigger;PlanetChildJourney.validateNodes(journeyId,nodeIds);this.nodeIds=Collections.unmodifiableList(new ArrayList<>(nodeIds));
        }
        String key(){return programId+"\n"+programVersion+"\n"+programChecksum+"\n"+reviewChecksum+"\n"+badgeId+"\n"+ruleVersion+"\n"+journeyId+"\n"+journeyVersion+"\n"+contentVersion;}
        @Override public boolean equals(Object raw){if(!(raw instanceof Award))return false;Award a=(Award)raw;return key().equals(a.key())&&reviewChecksum.equals(a.reviewChecksum)&&trigger.equals(a.trigger)&&nodeIds.equals(a.nodeIds);}
        @Override public int hashCode(){return Objects.hash(key(),reviewChecksum,trigger,nodeIds);}
    }
    /** Actual bounded canonical admitted text graph bytes are encrypted with the ledger. */
    static final class Route {
        final String journeyId,packageId,packageChecksum,reviewChecksum,policyVersion,policyChecksum,locale,platform,territory,snapshotChecksum;final long journeyVersion,contentVersion,packageVersion;final int exactAge;private final byte[] snapshot;
        Route(String id,long journeyVersion,long contentVersion,String packageId,long packageVersion,String packageChecksum,String reviewChecksum,String policyVersion,String policyChecksum,String locale,int exactAge,String platform,String territory,byte[] bytes)throws Exception {
            journeyId=PlanetChildJourney.identifier(id);this.journeyVersion=version(journeyVersion);this.contentVersion=version(contentVersion);this.packageId=PlanetChildJourney.identifier(packageId);this.packageVersion=version(packageVersion);this.packageChecksum=hash(packageChecksum);this.reviewChecksum=hash(reviewChecksum);this.policyVersion=PlanetChildJourney.identifier(policyVersion);this.policyChecksum=hash(policyChecksum);require(Arrays.asList("ru","en").contains(locale)&&exactAge>=3&&exactAge<=17&&Arrays.asList("android-google","android-rustore","ios-ipados").contains(platform)&&territory!=null&&territory.matches("[A-Z]{2}"));this.locale=locale;this.exactAge=exactAge;this.platform=platform;this.territory=territory;require(bytes!=null&&bytes.length>0&&bytes.length<=MAX_ROUTE_BYTES);require(journeyId.equals(PlanetChildVault.validatePassportRouteSnapshot(bytes)));snapshot=bytes.clone();snapshotChecksum=digest(snapshot);
        }
        int byteLength(){return snapshot.length;}
        byte[] copy(){return snapshot.clone();}
        Route detached()throws Exception {return new Route(journeyId,journeyVersion,contentVersion,packageId,packageVersion,packageChecksum,reviewChecksum,policyVersion,policyChecksum,locale,exactAge,platform,territory,snapshot);}
        void wipe(){Arrays.fill(snapshot,(byte)0);}
        @Override public boolean equals(Object raw){if(!(raw instanceof Route))return false;Route r=(Route)raw;return journeyId.equals(r.journeyId)&&journeyVersion==r.journeyVersion&&contentVersion==r.contentVersion&&packageId.equals(r.packageId)&&packageVersion==r.packageVersion&&packageChecksum.equals(r.packageChecksum)&&reviewChecksum.equals(r.reviewChecksum)&&policyVersion.equals(r.policyVersion)&&policyChecksum.equals(r.policyChecksum)&&locale.equals(r.locale)&&exactAge==r.exactAge&&platform.equals(r.platform)&&territory.equals(r.territory)&&snapshotChecksum.equals(r.snapshotChecksum)&&java.security.MessageDigest.isEqual(snapshot,r.snapshot);}
        @Override public int hashCode(){return Objects.hash(journeyId,journeyVersion,contentVersion,packageChecksum,locale,snapshotChecksum);}
    }
    private static long version(long value)throws Exception {require(value>0&&value<PlanetChildAppearance.MAX_SAFE);return value;}
    private static String hash(String value)throws Exception {require(value!=null&&value.matches("[a-f0-9]{64}"));return value;}
    private static String digest(byte[] bytes)throws Exception {byte[] d=java.security.MessageDigest.getInstance("SHA-256").digest(bytes);try{StringBuilder s=new StringBuilder(64);for(byte b:d)s.append(String.format(java.util.Locale.ROOT,"%02x",b&255));return s.toString();}finally{Arrays.fill(d,(byte)0);}}

    static final class Ledger {
        final List<String> countries;final List<Credit> credits;final List<CompletedJourney> completedJourneys;final List<Award> awards;final List<Route> routes;
        Ledger(List<String> countries,List<Credit> credits)throws Exception {this(countries,credits,Collections.emptyList());}
        Ledger(List<String> countries,List<Credit> credits,List<CompletedJourney> completedJourneys) throws Exception {this(countries,credits,completedJourneys,Collections.emptyList(),Collections.emptyList());}
        Ledger(List<String> countries,List<Credit> credits,List<CompletedJourney> completedJourneys,List<Award> awards,List<Route> routes) throws Exception {
            require(countries!=null&&credits!=null&&countries.size()<=MAX_IDS&&credits.size()<=MAX_IDS);
            Set<String> seen=new HashSet<>();ArrayList<String> ids=new ArrayList<>();for(String id:countries){PlanetChildJourney.identifier(id);require(seen.add(id));ids.add(id);}this.countries=Collections.unmodifiableList(ids);
            seen.clear();ArrayList<Credit> learning=new ArrayList<>();for(Credit credit:credits){require(credit!=null&&seen.add(credit.key()));learning.add(credit);}this.credits=Collections.unmodifiableList(learning);require(completedJourneys!=null&&completedJourneys.size()<=32);seen.clear();ArrayList<CompletedJourney> finished=new ArrayList<>();for(CompletedJourney receipt:completedJourneys){require(receipt!=null&&seen.add(receipt.key()));finished.add(receipt);}this.completedJourneys=Collections.unmodifiableList(finished);
            require(awards!=null&&awards.size()<=MAX_AWARDS&&routes!=null&&routes.size()<=MAX_ROUTES);seen.clear();ArrayList<Award> earned=new ArrayList<>();for(Award award:awards){require(award!=null&&seen.add(award.key()));earned.add(award);}this.awards=Collections.unmodifiableList(earned);seen.clear();int total=0;ArrayList<Route> saved=new ArrayList<>();for(Route route:routes){require(route!=null&&seen.add(route.journeyId)&&route.byteLength()<=MAX_ROUTE_BYTES);total+=route.byteLength();require(total<=MAX_ROUTE_TOTAL);saved.add(route);}this.routes=Collections.unmodifiableList(saved);
        }
        Ledger opened(String country) throws Exception {ArrayList<String> ids=new ArrayList<>(countries);if(!ids.contains(country)){require(ids.size()<MAX_IDS);ids.add(country);}return new Ledger(ids,credits,completedJourneys,awards,routes);}
        Ledger learned(Credit credit) throws Exception {if(credit==null)return this;ArrayList<Credit> next=new ArrayList<>(credits);for(Credit old:next)if(old.key().equals(credit.key())){require(old.kind.equals(credit.kind)&&old.entityId.equals(credit.entityId));return this;}require(next.size()<MAX_IDS);next.add(credit);return new Ledger(countries,next,completedJourneys,awards,routes);}

        Ledger finished(CompletedJourney receipt)throws Exception {if(receipt==null)return this;ArrayList<CompletedJourney> next=new ArrayList<>(completedJourneys);for(CompletedJourney old:next)if(old.key().equals(receipt.key())){require(old.equals(receipt));return this;}require(next.size()<32);next.add(receipt);return new Ledger(countries,credits,next,awards,routes);}
        boolean confirms(Award award)throws Exception {if("completed-journey".equals(award.trigger)){boolean found=false;for(CompletedJourney receipt:completedJourneys)if(receipt.journeyId.equals(award.journeyId)&&receipt.journeyVersion==award.journeyVersion&&receipt.contentVersion==award.contentVersion&&receipt.nodeIds.containsAll(award.nodeIds))found=true;return found;}for(String node:award.nodeIds){boolean found=false;for(Credit credit:credits)if(credit.journeyId.equals(award.journeyId)&&credit.journeyVersion==award.journeyVersion&&credit.contentVersion==award.contentVersion&&credit.nodeId.equals(node))found=true;if(!found)return false;}return true;}
        Ledger awarded(Award award)throws Exception {ArrayList<Award> next=new ArrayList<>(awards);for(Award old:next)if(old.key().equals(award.key())){require(old.equals(award));return this;}require(next.size()<MAX_AWARDS);next.add(award);return new Ledger(countries,credits,completedJourneys,next,routes);}
        Ledger saved(Route route)throws Exception {ArrayList<Route> next=new ArrayList<>(routes);int index=-1;for(int i=0;i<next.size();i++)if(next.get(i).journeyId.equals(route.journeyId))index=i;if(index<0){require(next.size()<MAX_ROUTES);next.add(route);}else next.set(index,route);return new Ledger(countries,credits,completedJourneys,awards,next);}
        Ledger clearedRoutes()throws Exception {return new Ledger(countries,credits,completedJourneys,awards,Collections.emptyList());}
        Ledger detached()throws Exception {ArrayList<Route> next=new ArrayList<>();try{for(Route route:routes)next.add(route.detached());return new Ledger(countries,credits,completedJourneys,awards,next);}catch(Exception failure){for(Route route:next)route.wipe();throw failure;}}
        void wipe(){for(Route route:routes)route.wipe();}
        @Override public boolean equals(Object raw){return raw instanceof Ledger&&countries.equals(((Ledger)raw).countries)&&credits.equals(((Ledger)raw).credits)&&completedJourneys.equals(((Ledger)raw).completedJourneys)&&awards.equals(((Ledger)raw).awards)&&routes.equals(((Ledger)raw).routes);}
        @Override public int hashCode(){return Objects.hash(countries,credits,completedJourneys,awards,routes);}
        byte[] encode() throws Exception {ByteArrayOutputStream bytes=new ByteArrayOutputStream();DataOutputStream out=new DataOutputStream(bytes);out.writeInt(0x4c505031);out.writeByte(1);out.writeShort(countries.size());for(String id:countries)out.writeUTF(id);out.writeShort(credits.size());for(Credit c:credits){out.writeUTF(c.journeyId);out.writeUTF(c.nodeId);out.writeUTF(c.kind);out.writeUTF(c.entityId);out.writeLong(c.journeyVersion);out.writeLong(c.contentVersion);}out.writeByte(completedJourneys.size());for(CompletedJourney j:completedJourneys){out.writeUTF(j.journeyId);out.writeLong(j.journeyVersion);out.writeLong(j.contentVersion);out.writeByte(j.nodeIds.size());for(String id:j.nodeIds)out.writeUTF(id);}if(!awards.isEmpty()||!routes.isEmpty()){out.writeInt(0x4c504232);out.writeByte(1);out.writeShort(awards.size());for(Award a:awards){out.writeUTF(a.programId);out.writeLong(a.programVersion);out.writeUTF(a.programChecksum);out.writeUTF(a.reviewChecksum);out.writeUTF(a.badgeId);out.writeLong(a.ruleVersion);out.writeUTF(a.journeyId);out.writeLong(a.journeyVersion);out.writeLong(a.contentVersion);out.writeUTF(a.trigger);out.writeByte(a.nodeIds.size());for(String id:a.nodeIds)out.writeUTF(id);}out.writeByte(routes.size());for(Route r:routes){out.writeUTF(r.journeyId);out.writeLong(r.journeyVersion);out.writeLong(r.contentVersion);out.writeUTF(r.packageId);out.writeLong(r.packageVersion);out.writeUTF(r.packageChecksum);out.writeUTF(r.reviewChecksum);out.writeUTF(r.policyVersion);out.writeUTF(r.policyChecksum);out.writeUTF(r.locale);out.writeByte(r.exactAge);out.writeUTF(r.platform);out.writeUTF(r.territory);out.writeUTF(r.snapshotChecksum);byte[] b=r.copy();try{require(digest(b).equals(r.snapshotChecksum));out.writeInt(b.length);out.write(b);}finally{Arrays.fill(b,(byte)0);}}}out.flush();byte[] result=bytes.toByteArray();require(result.length<=MAX_BYTES);return result;}
    }
    static Ledger empty() throws Exception {return new Ledger(Collections.emptyList(),Collections.emptyList());}
    static Ledger decode(byte[] bytes) throws Exception {require(bytes!=null&&bytes.length>0&&bytes.length<=MAX_BYTES);DataInputStream in=new DataInputStream(new ByteArrayInputStream(bytes));require(in.readInt()==0x4c505031&&in.readUnsignedByte()==1);int count=in.readUnsignedShort();require(count<=MAX_IDS);List<String> countries=new ArrayList<>();for(int i=0;i<count;i++)countries.add(in.readUTF());count=in.readUnsignedShort();require(count<=MAX_IDS);List<Credit> credits=new ArrayList<>();for(int i=0;i<count;i++)credits.add(new Credit(in.readUTF(),in.readUTF(),in.readUTF(),in.readUTF(),in.readLong(),in.readLong()));int n=in.readUnsignedByte();require(n<=32);List<CompletedJourney> finished=new ArrayList<>();for(int i=0;i<n;i++){String id=in.readUTF();long journey=in.readLong(),content=in.readLong();int k=in.readUnsignedByte();require(k>0&&k<=64);List<String> nodes=new ArrayList<>();for(int j=0;j<k;j++)nodes.add(in.readUTF());finished.add(new CompletedJourney(id,journey,content,nodes));}List<Award> awards=new ArrayList<>();List<Route> routes=new ArrayList<>();try{if(in.available()>0){require(in.readInt()==0x4c504232&&in.readUnsignedByte()==1);int countAwards=in.readUnsignedShort();require(countAwards<=MAX_AWARDS);for(int i=0;i<countAwards;i++){String pid=in.readUTF();long pv=in.readLong();String ph=in.readUTF(),rh=in.readUTF(),bid=in.readUTF();long rv=in.readLong();String jid=in.readUTF();long jv=in.readLong(),cv=in.readLong();String trigger=in.readUTF();int size=in.readUnsignedByte();require(size>0&&size<=64);List<String> nodes=new ArrayList<>();for(int j=0;j<size;j++)nodes.add(in.readUTF());awards.add(new Award(pid,pv,ph,rh,bid,rv,jid,jv,cv,trigger,nodes));}int countRoutes=in.readUnsignedByte();require(countRoutes<=MAX_ROUTES);int total=0;for(int i=0;i<countRoutes;i++){String id=in.readUTF();long jv=in.readLong(),cv=in.readLong();String packageId=in.readUTF();long packageVersion=in.readLong();String packageHash=in.readUTF(),reviewHash=in.readUTF(),policy=in.readUTF(),policyHash=in.readUTF(),locale=in.readUTF();int age=in.readUnsignedByte();String platform=in.readUTF(),territory=in.readUTF(),hash=in.readUTF();int length=in.readInt();require(length>0&&length<=MAX_ROUTE_BYTES&&length<=in.available());total+=length;require(total<=MAX_ROUTE_TOTAL);byte[] b=new byte[length];try{in.readFully(b);require(digest(b).equals(hash));routes.add(new Route(id,jv,cv,packageId,packageVersion,packageHash,reviewHash,policy,policyHash,locale,age,platform,territory,b));}finally{Arrays.fill(b,(byte)0);}}require(!awards.isEmpty()||!routes.isEmpty());}require(in.available()==0);Ledger ledger=new Ledger(countries,credits,finished,awards,routes);byte[] exact=ledger.encode();try{require(Arrays.equals(bytes,exact));}finally{Arrays.fill(exact,(byte)0);}return ledger;}catch(Exception failure){for(Route route:routes)route.wipe();throw failure;}}
}
