// Generated by scripts/export-published-content.mjs. Do not edit by hand.
// Durable country-profile overrides saved from the editorial database.
export const cmsCountryProfileOverrides = {} as const;
