// Generated by scripts/export-premium-translations.mjs. Do not edit by hand.
// Durable country-profile overrides plus reviewed English localizations.
export const cmsCountryProfileOverrides = {} as const;
