import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { fileURLToPath } from "node:url";
import { cmsLiteraryWorkProfilesForWriter, type CmsLiteraryWork } from "./editorialOverrides";

// The September 12 byte-proofs included these 17 public CMS records. Read their
// immutable Git blob, not the generated file which a fresh export can replace.
// Both quality and Pages build check out full history for historical proofs.
const source = execFileSync("git", [
  "show", "d6c7849ccc5285e17c6da9ef147fecc9fdd0f000:src/data/cms/literaryWorks.generated.ts",
], { cwd: fileURLToPath(new URL("../../../", import.meta.url)), maxBuffer: 128 * 1024 });
if (createHash("sha256").update(source).digest("hex") !==
  "6634bf7a357e7b1cfd1859d1194b66f355a8d6b1814da8342d9c75c3adcff2dd") {
  throw new Error("Historical literary-work CMS source fingerprint changed");
}
const prefix = "// Generated by scripts/export-premium-translations.mjs. Do not edit by hand.\n" +
  "// Published literary works with reviewed Russian and English text plus provenance.\n" +
  "export const cmsLiteraryWorksByLegacyId = ";
const text = source.toString("utf8");
const suffix = " as const;\n";
if (!text.startsWith(prefix) || !text.endsWith(suffix)) {
  throw new Error("Historical literary-work CMS initializer is not the pinned JSON shape");
}
const works = JSON.parse(text.slice(prefix.length, -suffix.length)) as Record<string, CmsLiteraryWork>;
if (Object.keys(works).length !== 17 || Object.entries(works).some(([key, work]) =>
  key !== work.legacyId || key !== `${work.countryId}:${work.writerId}:${work.localId}`)) {
  throw new Error("Historical literary-work CMS identity set changed");
}
// Capture the real mapper before the caller installs a temporary spy.
const mapProfiles = cmsLiteraryWorkProfilesForWriter;
export function historicalCmsLiteraryWorkProfilesForWriter(countryId: string, writerId: string) {
  return mapProfiles(countryId, writerId, works);
}
