// Generated by scripts/export-premium-translations.mjs. Do not edit by hand.
// Published literary works with reviewed Russian and English text plus provenance.
export const cmsLiteraryWorksByLegacyId = {
  "england:david_mitchell:ghostwritten": {
    "legacyId": "england:david_mitchell:ghostwritten",
    "countryId": "england",
    "writerId": "david_mitchell",
    "localId": "ghostwritten",
    "title": "Литературный призрак",
    "originalTitle": "Ghostwritten",
    "firstPublished": 1999,
    "originalLanguage": "английский",
    "genres": [
      "роман",
      "современная проза"
    ],
    "tags": [
      "связанные истории",
      "глобальный роман",
      "идентичность",
      "случай",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Девять голосов ведут повествование через Восточную Азию, Россию, Европу и США, постепенно обнаруживая связи между на первый взгляд отдельными судьбами. Дебютный роман исследует случай, ответственность и движение историй через границы культур и сознаний.",
    "sourceUrl": "https://openlibrary.org/works/OL271981W",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "Ghostwritten",
        "description": "Nine voices carry the narrative across East Asia, Russia, Europe, and the United States, gradually revealing connections among apparently separate lives. The debut novel examines chance, responsibility, and the movement of stories across cultural and mental borders.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL271981W",
          "https://davidmitchellbooks.com/books/"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "Литературный призрак",
        "description": "Девять голосов ведут повествование через Восточную Азию, Россию, Европу и США, постепенно обнаруживая связи между на первый взгляд отдельными судьбами. Дебютный роман исследует случай, ответственность и движение историй через границы культур и сознаний.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL271981W",
          "https://davidmitchellbooks.com/books/"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "David Mitchell official site",
        "url": "https://davidmitchellbooks.com/books/",
        "fields": [
          "identity",
          "authorship",
          "title",
          "description"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      },
      {
        "provider": "Open Library",
        "url": "https://openlibrary.org/works/OL271981W",
        "fields": [
          "identity",
          "authorship",
          "title",
          "original-title",
          "publication-year",
          "language"
        ],
        "usage": "structured-data",
        "retrievedAt": "2026-08-20"
      }
    ]
  },
  "england:david_mitchell:number9dream": {
    "legacyId": "england:david_mitchell:number9dream",
    "countryId": "england",
    "writerId": "david_mitchell",
    "localId": "number9dream",
    "title": "Сон № 9",
    "originalTitle": "Number9Dream",
    "firstPublished": 2001,
    "originalLanguage": "английский",
    "genres": [
      "роман",
      "современная проза"
    ],
    "tags": [
      "Токио",
      "поиск отца",
      "сны",
      "идентичность",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Юный Эйдзи Миякэ приезжает в Токио, чтобы разыскать отца, которого никогда не знал, и оказывается между городской реальностью, фантазиями и снами. Поиск происхождения превращается в историю взросления, где память и вымысел постоянно меняют значение происходящего.",
    "sourceUrl": "https://openlibrary.org/works/OL271980W",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "Number9Dream",
        "description": "Young Eiji Miyake comes to Tokyo to find the father he has never known and moves between urban reality, fantasy, and dreams. His search for origins becomes a coming-of-age story in which memory and invention repeatedly alter the meaning of events.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL271980W",
          "https://davidmitchellbooks.com/books/"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "Сон № 9",
        "description": "Юный Эйдзи Миякэ приезжает в Токио, чтобы разыскать отца, которого никогда не знал, и оказывается между городской реальностью, фантазиями и снами. Поиск происхождения превращается в историю взросления, где память и вымысел постоянно меняют значение происходящего.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL271980W",
          "https://davidmitchellbooks.com/books/"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "David Mitchell official site",
        "url": "https://davidmitchellbooks.com/books/",
        "fields": [
          "identity",
          "authorship",
          "title",
          "description"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      },
      {
        "provider": "Open Library",
        "url": "https://openlibrary.org/works/OL271980W",
        "fields": [
          "identity",
          "authorship",
          "title",
          "original-title",
          "publication-year",
          "language"
        ],
        "usage": "structured-data",
        "retrievedAt": "2026-08-20"
      }
    ]
  },
  "england:david_mitchell:slade-house": {
    "legacyId": "england:david_mitchell:slade-house",
    "countryId": "england",
    "writerId": "david_mitchell",
    "localId": "slade-house",
    "title": "Голодный дом",
    "originalTitle": "Slade House",
    "firstPublished": 2015,
    "originalLanguage": "английский",
    "genres": [
      "роман",
      "готическая проза",
      "фэнтези"
    ],
    "tags": [
      "дом с привидениями",
      "девятилетний цикл",
      "исчезновения",
      "бессмертие",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Неприметная дверь в лондонском переулке раз в девять лет впускает нового гостя в дом, из которого почти невозможно выбраться. Пять связанных эпизодов переосмысляют историю дома с привидениями через память, хищное бессмертие и повторяющуюся ловушку.",
    "sourceUrl": "https://openlibrary.org/works/OL17801648W",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "Slade House",
        "description": "An inconspicuous door in a London alley admits a new guest every nine years into a house that is almost impossible to leave. Five linked episodes recast the haunted-house story through memory, predatory immortality, and a repeating trap.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL17801648W",
          "https://davidmitchellbooks.com/books/"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "Голодный дом",
        "description": "Неприметная дверь в лондонском переулке раз в девять лет впускает нового гостя в дом, из которого почти невозможно выбраться. Пять связанных эпизодов переосмысляют историю дома с привидениями через память, хищное бессмертие и повторяющуюся ловушку.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL17801648W",
          "https://davidmitchellbooks.com/books/"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "David Mitchell official site",
        "url": "https://davidmitchellbooks.com/books/",
        "fields": [
          "identity",
          "authorship",
          "title",
          "description"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      },
      {
        "provider": "Open Library",
        "url": "https://openlibrary.org/works/OL17801648W",
        "fields": [
          "identity",
          "authorship",
          "title",
          "original-title",
          "publication-year",
          "language"
        ],
        "usage": "structured-data",
        "retrievedAt": "2026-08-20"
      }
    ]
  },
  "england:david_mitchell:the-bone-clocks": {
    "legacyId": "england:david_mitchell:the-bone-clocks",
    "countryId": "england",
    "writerId": "david_mitchell",
    "localId": "the-bone-clocks",
    "title": "Костяные часы",
    "originalTitle": "The Bone Clocks",
    "firstPublished": 2014,
    "originalLanguage": "английский",
    "genres": [
      "роман",
      "фэнтези",
      "современная проза"
    ],
    "tags": [
      "Холли Сайкс",
      "время",
      "бессмертие",
      "связанные истории",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Жизнь Холли Сайкс прослеживается на протяжении десятилетий, от подросткового побега до старости в изменившемся мире. За частной биографией постепенно раскрывается тайная борьба групп, по-разному понимающих бессмертие, память и цену человеческой жизни.",
    "sourceUrl": "https://openlibrary.org/works/OL17078738W",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "The Bone Clocks",
        "description": "Holly Sykes's life unfolds across decades, from a teenage escape to old age in a transformed world. Behind her personal history, a hidden conflict gradually emerges between groups with opposing ideas about immortality, memory, and the value of human life.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL17078738W",
          "https://davidmitchellbooks.com/books/",
          "https://azbooka.ru/books/kostyanye-chasy"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "Костяные часы",
        "description": "Жизнь Холли Сайкс прослеживается на протяжении десятилетий, от подросткового побега до старости в изменившемся мире. За частной биографией постепенно раскрывается тайная борьба групп, по-разному понимающих бессмертие, память и цену человеческой жизни.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL17078738W",
          "https://davidmitchellbooks.com/books/",
          "https://azbooka.ru/books/kostyanye-chasy"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "Azbooka-Atticus",
        "url": "https://azbooka.ru/books/kostyanye-chasy",
        "fields": [
          "identity",
          "authorship",
          "title",
          "description"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      },
      {
        "provider": "David Mitchell official site",
        "url": "https://davidmitchellbooks.com/books/",
        "fields": [
          "identity",
          "authorship",
          "title",
          "description"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      },
      {
        "provider": "Open Library",
        "url": "https://openlibrary.org/works/OL17078738W",
        "fields": [
          "identity",
          "authorship",
          "title",
          "original-title",
          "publication-year",
          "language"
        ],
        "usage": "structured-data",
        "retrievedAt": "2026-08-20"
      }
    ]
  },
  "england:david_mitchell:the-thousand-autumns-of-jacob-de-zoet": {
    "legacyId": "england:david_mitchell:the-thousand-autumns-of-jacob-de-zoet",
    "countryId": "england",
    "writerId": "david_mitchell",
    "localId": "the-thousand-autumns-of-jacob-de-zoet",
    "title": "Тысяча осеней Якоба де Зута",
    "originalTitle": "The Thousand Autumns of Jacob de Zoet",
    "firstPublished": 2010,
    "originalLanguage": "английский",
    "genres": [
      "исторический роман",
      "современная проза"
    ],
    "tags": [
      "Дэдзима",
      "Япония",
      "торговля",
      "власть",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Голландский клерк Якоб де Зут прибывает на торговый остров Дэдзима в конце XVIII века и сталкивается с коррупцией, культурными границами и запретной привязанностью. Исторический роман соединяет частную судьбу с конфликтом имперской торговли, медицины и закрытого общества.",
    "sourceUrl": "https://openlibrary.org/works/OL15233654W",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "The Thousand Autumns of Jacob de Zoet",
        "description": "Dutch clerk Jacob de Zoet arrives at the trading island of Dejima at the end of the eighteenth century and encounters corruption, cultural boundaries, and forbidden attachment. The historical novel joins a private fate to conflicts involving imperial commerce, medicine, and a closed society.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL15233654W",
          "https://davidmitchellbooks.com/books/"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "Тысяча осеней Якоба де Зута",
        "description": "Голландский клерк Якоб де Зут прибывает на торговый остров Дэдзима в конце XVIII века и сталкивается с коррупцией, культурными границами и запретной привязанностью. Исторический роман соединяет частную судьбу с конфликтом имперской торговли, медицины и закрытого общества.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL15233654W",
          "https://davidmitchellbooks.com/books/"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "David Mitchell official site",
        "url": "https://davidmitchellbooks.com/books/",
        "fields": [
          "identity",
          "authorship",
          "title",
          "description"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      },
      {
        "provider": "Open Library",
        "url": "https://openlibrary.org/works/OL15233654W",
        "fields": [
          "identity",
          "authorship",
          "title",
          "original-title",
          "publication-year",
          "language"
        ],
        "usage": "structured-data",
        "retrievedAt": "2026-08-20"
      }
    ]
  },
  "england:h_g_wells:ann-veronica": {
    "legacyId": "england:h_g_wells:ann-veronica",
    "countryId": "england",
    "writerId": "h_g_wells",
    "localId": "ann-veronica",
    "title": "Анна-Вероника",
    "originalTitle": "Ann Veronica",
    "firstPublished": 1909,
    "originalLanguage": "английский",
    "genres": [
      "роман",
      "социальная проза"
    ],
    "tags": [
      "женская независимость",
      "образование",
      "суфражизм",
      "Лондон",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Молодая Анна Вероника покидает отцовский дом, чтобы самостоятельно учиться и жить в Лондоне, несмотря на общественные и семейные запреты. Роман связывает личное взросление героини с дискуссиями о женском образовании, труде, любви и политической свободе.",
    "sourceUrl": "https://openlibrary.org/works/OL52258W",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "Ann Veronica",
        "description": "Young Ann Veronica leaves her father's home to study and live independently in London despite family and social restrictions. The novel connects her personal maturation with debates about women's education, work, love, and political freedom.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL52258W",
          "https://www.gutenberg.org/ebooks/author/30?sort_order=downloads"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "Анна-Вероника",
        "description": "Молодая Анна Вероника покидает отцовский дом, чтобы самостоятельно учиться и жить в Лондоне, несмотря на общественные и семейные запреты. Роман связывает личное взросление героини с дискуссиями о женском образовании, труде, любви и политической свободе.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL52258W",
          "https://www.gutenberg.org/ebooks/author/30?sort_order=downloads"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "Open Library",
        "url": "https://openlibrary.org/works/OL52258W",
        "fields": [
          "identity",
          "authorship",
          "title",
          "original-title",
          "publication-year",
          "language"
        ],
        "usage": "structured-data",
        "retrievedAt": "2026-08-20"
      },
      {
        "provider": "Project Gutenberg",
        "url": "https://www.gutenberg.org/ebooks/author/30?sort_order=downloads",
        "fields": [
          "identity",
          "authorship",
          "title",
          "language"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      }
    ]
  },
  "england:h_g_wells:men-like-gods": {
    "legacyId": "england:h_g_wells:men-like-gods",
    "countryId": "england",
    "writerId": "h_g_wells",
    "localId": "men-like-gods",
    "title": "Люди как боги",
    "originalTitle": "Men Like Gods",
    "firstPublished": 1923,
    "originalLanguage": "английский",
    "genres": [
      "научно-фантастический роман",
      "утопия"
    ],
    "tags": [
      "параллельный мир",
      "утопия",
      "наука",
      "политика",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Журналист Барнстейпл и несколько случайных спутников попадают в параллельный мир Утопию, где наука и общественное устройство развивались без привычных земных институтов. Столкновение миров проверяет не только утопический идеал, но и стремление гостей навязать ему собственную власть.",
    "sourceUrl": "https://openlibrary.org/works/OL52237W",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "Men Like Gods",
        "description": "Journalist Barnstaple and several accidental companions enter a parallel world called Utopia, where science and social organization developed without familiar earthly institutions. The encounter tests both the utopian ideal and the visitors' impulse to impose their own authority upon it.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL52237W"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "Люди как боги",
        "description": "Журналист Барнстейпл и несколько случайных спутников попадают в параллельный мир Утопию, где наука и общественное устройство развивались без привычных земных институтов. Столкновение миров проверяет не только утопический идеал, но и стремление гостей навязать ему собственную власть.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL52237W"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "Open Library",
        "url": "https://openlibrary.org/works/OL52237W",
        "fields": [
          "identity",
          "authorship",
          "title",
          "original-title",
          "publication-year",
          "language"
        ],
        "usage": "structured-data",
        "retrievedAt": "2026-08-20"
      }
    ]
  },
  "england:h_g_wells:the-first-men-in-the-moon": {
    "legacyId": "england:h_g_wells:the-first-men-in-the-moon",
    "countryId": "england",
    "writerId": "h_g_wells",
    "localId": "the-first-men-in-the-moon",
    "title": "Первые люди на Луне",
    "originalTitle": "The First Men in the Moon",
    "firstPublished": 1901,
    "originalLanguage": "английский",
    "genres": [
      "научно-фантастический роман",
      "приключенческая проза"
    ],
    "tags": [
      "Луна",
      "космическое путешествие",
      "селениты",
      "наука",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Изобретатель Кэйвор создаёт вещество, нейтрализующее гравитацию, и вместе с деловым Бедфордом отправляется на Луну. Встреча с подземной цивилизацией селенитов превращает приключение в сатиру на земное общество, специализацию и империализм.",
    "sourceUrl": "https://openlibrary.org/works/OL52260W",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "The First Men in the Moon",
        "description": "Inventor Cavor creates a substance that cancels gravity and travels to the Moon with the commercially minded Bedford. Their encounter with the subterranean Selenites turns an adventure into a satire on earthly society, specialization, and imperial ambition.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL52260W",
          "https://www.gutenberg.org/ebooks/author/30?sort_order=downloads"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "Первые люди на Луне",
        "description": "Изобретатель Кэйвор создаёт вещество, нейтрализующее гравитацию, и вместе с деловым Бедфордом отправляется на Луну. Встреча с подземной цивилизацией селенитов превращает приключение в сатиру на земное общество, специализацию и империализм.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL52260W",
          "https://www.gutenberg.org/ebooks/author/30?sort_order=downloads"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "Open Library",
        "url": "https://openlibrary.org/works/OL52260W",
        "fields": [
          "identity",
          "authorship",
          "title",
          "original-title",
          "publication-year",
          "language"
        ],
        "usage": "structured-data",
        "retrievedAt": "2026-08-20"
      },
      {
        "provider": "Project Gutenberg",
        "url": "https://www.gutenberg.org/ebooks/author/30?sort_order=downloads",
        "fields": [
          "identity",
          "authorship",
          "title",
          "language"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      }
    ]
  },
  "england:h_g_wells:the-food-of-the-gods": {
    "legacyId": "england:h_g_wells:the-food-of-the-gods",
    "countryId": "england",
    "writerId": "h_g_wells",
    "localId": "the-food-of-the-gods",
    "title": "Пища богов",
    "originalTitle": "The Food of the Gods and How It Came to Earth",
    "firstPublished": 1904,
    "originalLanguage": "английский",
    "genres": [
      "научно-фантастический роман",
      "социальная сатира"
    ],
    "tags": [
      "рост",
      "научный эксперимент",
      "гиганты",
      "общественный конфликт",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Экспериментальная пища вызывает неуправляемый рост растений, животных и детей, создавая поколение гигантов. Уэллс превращает биологическое допущение в конфликт между новым масштабом жизни и обществом, которое пытается сохранить привычный порядок.",
    "sourceUrl": "https://openlibrary.org/works/OL52195W",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "The Food of the Gods and How It Came to Earth",
        "description": "An experimental food causes uncontrolled growth in plants, animals, and children, producing a generation of giants. Wells turns the biological premise into a conflict between a new scale of life and a society determined to preserve its familiar order.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL52195W",
          "https://www.gutenberg.org/ebooks/author/30?sort_order=downloads"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "Пища богов",
        "description": "Экспериментальная пища вызывает неуправляемый рост растений, животных и детей, создавая поколение гигантов. Уэллс превращает биологическое допущение в конфликт между новым масштабом жизни и обществом, которое пытается сохранить привычный порядок.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL52195W",
          "https://www.gutenberg.org/ebooks/author/30?sort_order=downloads"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "Open Library",
        "url": "https://openlibrary.org/works/OL52195W",
        "fields": [
          "identity",
          "authorship",
          "title",
          "original-title",
          "publication-year",
          "language"
        ],
        "usage": "structured-data",
        "retrievedAt": "2026-08-20"
      },
      {
        "provider": "Project Gutenberg",
        "url": "https://www.gutenberg.org/ebooks/author/30?sort_order=downloads",
        "fields": [
          "identity",
          "authorship",
          "title",
          "language"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      }
    ]
  },
  "england:h_g_wells:the-history-of-mr-polly": {
    "legacyId": "england:h_g_wells:the-history-of-mr-polly",
    "countryId": "england",
    "writerId": "h_g_wells",
    "localId": "the-history-of-mr-polly",
    "title": "История мистера Полли",
    "originalTitle": "The History of Mr. Polly",
    "firstPublished": 1910,
    "originalLanguage": "английский",
    "genres": [
      "роман",
      "социальная комедия"
    ],
    "tags": [
      "маленький человек",
      "лавочник",
      "побег",
      "самоопределение",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Разочарованный лавочник Альфред Полли чувствует себя пленником неудачного брака, бедности и случайно выбранного занятия. Неудачная попытка уничтожить прежнюю жизнь приводит его к неожиданному побегу и возможности заново определить собственное место.",
    "sourceUrl": "https://openlibrary.org/works/OL52262W",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "The History of Mr. Polly",
        "description": "Disappointed shopkeeper Alfred Polly feels trapped by an unhappy marriage, poverty, and an occupation chosen almost by accident. His failed attempt to destroy his former life leads to an unexpected escape and a chance to define his place anew.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL52262W",
          "https://www.gutenberg.org/ebooks/author/30?sort_order=downloads"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "История мистера Полли",
        "description": "Разочарованный лавочник Альфред Полли чувствует себя пленником неудачного брака, бедности и случайно выбранного занятия. Неудачная попытка уничтожить прежнюю жизнь приводит его к неожиданному побегу и возможности заново определить собственное место.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL52262W",
          "https://www.gutenberg.org/ebooks/author/30?sort_order=downloads"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "Open Library",
        "url": "https://openlibrary.org/works/OL52262W",
        "fields": [
          "identity",
          "authorship",
          "title",
          "original-title",
          "publication-year",
          "language"
        ],
        "usage": "structured-data",
        "retrievedAt": "2026-08-20"
      },
      {
        "provider": "Project Gutenberg",
        "url": "https://www.gutenberg.org/ebooks/author/30?sort_order=downloads",
        "fields": [
          "identity",
          "authorship",
          "title",
          "language"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      }
    ]
  },
  "england:h_g_wells:the-world-set-free": {
    "legacyId": "england:h_g_wells:the-world-set-free",
    "countryId": "england",
    "writerId": "h_g_wells",
    "localId": "the-world-set-free",
    "title": "Освобождённый мир",
    "originalTitle": "The World Set Free",
    "firstPublished": 1914,
    "originalLanguage": "английский",
    "genres": [
      "научно-фантастический роман",
      "социальная фантастика"
    ],
    "tags": [
      "атомная энергия",
      "война",
      "мировое правительство",
      "будущее",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Открытие управляемой атомной энергии даёт человечеству новый источник силы, но вскоре приводит к мировой войне с продолжительными ядерными взрывами. После катастрофы роман воображает попытку построить международный порядок, способный ограничить национальное насилие.",
    "sourceUrl": "https://openlibrary.org/works/OL52257W",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "The World Set Free",
        "description": "The discovery of controllable atomic energy gives humanity a new source of power but soon leads to a world war fought with continuously exploding bombs. After catastrophe, the novel imagines an attempt to build an international order capable of restraining national violence.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL52257W",
          "https://www.gutenberg.org/ebooks/1059"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "Освобождённый мир",
        "description": "Открытие управляемой атомной энергии даёт человечеству новый источник силы, но вскоре приводит к мировой войне с продолжительными ядерными взрывами. После катастрофы роман воображает попытку построить международный порядок, способный ограничить национальное насилие.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL52257W",
          "https://www.gutenberg.org/ebooks/1059"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "Open Library",
        "url": "https://openlibrary.org/works/OL52257W",
        "fields": [
          "identity",
          "authorship",
          "title",
          "original-title",
          "publication-year",
          "language"
        ],
        "usage": "structured-data",
        "retrievedAt": "2026-08-20"
      },
      {
        "provider": "Project Gutenberg",
        "url": "https://www.gutenberg.org/ebooks/1059",
        "fields": [
          "identity",
          "authorship",
          "title",
          "publication-year",
          "language"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      }
    ]
  },
  "england:h_g_wells:when-the-sleeper-wakes": {
    "legacyId": "england:h_g_wells:when-the-sleeper-wakes",
    "countryId": "england",
    "writerId": "h_g_wells",
    "localId": "when-the-sleeper-wakes",
    "title": "Когда спящий проснётся",
    "originalTitle": "When the Sleeper Wakes",
    "firstPublished": 1899,
    "originalLanguage": "английский",
    "genres": [
      "научно-фантастический роман",
      "антиутопия"
    ],
    "tags": [
      "будущее",
      "власть",
      "массовое общество",
      "революция",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Грэм впадает в необычайно долгий сон и просыпается через два столетия владельцем состояния, на котором держится мировая власть. Его пробуждение превращается в политический кризис и проверку того, способен ли символ освобождения действовать самостоятельно.",
    "sourceUrl": "https://openlibrary.org/works/OL52151W",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "When the Sleeper Wakes",
        "description": "Graham falls into an extraordinary sleep and wakes two centuries later as the legal owner of a fortune underpinning global power. His return becomes a political crisis and a test of whether a symbol of liberation can act independently of those who control his image.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL52151W",
          "https://www.gutenberg.org/ebooks/author/30?sort_order=downloads"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "Когда спящий проснётся",
        "description": "Грэм впадает в необычайно долгий сон и просыпается через два столетия владельцем состояния, на котором держится мировая власть. Его пробуждение превращается в политический кризис и проверку того, способен ли символ освобождения действовать самостоятельно.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://openlibrary.org/works/OL52151W",
          "https://www.gutenberg.org/ebooks/author/30?sort_order=downloads"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "Open Library",
        "url": "https://openlibrary.org/works/OL52151W",
        "fields": [
          "identity",
          "authorship",
          "title",
          "original-title",
          "publication-year",
          "language"
        ],
        "usage": "structured-data",
        "retrievedAt": "2026-08-20"
      },
      {
        "provider": "Project Gutenberg",
        "url": "https://www.gutenberg.org/ebooks/author/30?sort_order=downloads",
        "fields": [
          "identity",
          "authorship",
          "title",
          "language"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      }
    ]
  },
  "russia:chekhov:the-black-monk": {
    "legacyId": "russia:chekhov:the-black-monk",
    "countryId": "russia",
    "writerId": "chekhov",
    "localId": "the-black-monk",
    "title": "Чёрный монах",
    "originalTitle": "Чёрный монах",
    "firstPublished": 1894,
    "originalLanguage": "русский",
    "genres": [
      "повесть",
      "психологическая проза"
    ],
    "tags": [
      "талант",
      "видения",
      "безумие",
      "сад",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Учёный Андрей Коврин приезжает отдыхать в усадьбу опекуна и начинает видеть чёрного монаха, который убеждает его в собственной избранности. История связывает творческое честолюбие, душевный разлад и разрушение близких отношений, не сводя видения героя к простой разгадке.",
    "sourceUrl": "https://chekhovmuseum.com/museum/objects/17/849?type=section",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "The Black Monk",
        "description": "Scholar Andrey Kovrin visits his former guardian's estate and begins seeing a black monk who assures him that he is one of humanity's chosen minds. The story binds artistic ambition, mental disturbance, and damaged intimacy without reducing Kovrin's visions to a simple answer.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://chekhovmuseum.com/museum/objects/17/849?type=section"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "Чёрный монах",
        "description": "Учёный Андрей Коврин приезжает отдыхать в усадьбу опекуна и начинает видеть чёрного монаха, который убеждает его в собственной избранности. История связывает творческое честолюбие, душевный разлад и разрушение близких отношений, не сводя видения героя к простой разгадке.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://chekhovmuseum.com/museum/objects/17/849?type=section"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "Chekhov Museum Melikhovo",
        "url": "https://chekhovmuseum.com/museum/objects/17/849?type=section",
        "fields": [
          "identity",
          "authorship",
          "title"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      }
    ]
  },
  "russia:chekhov:the-duel": {
    "legacyId": "russia:chekhov:the-duel",
    "countryId": "russia",
    "writerId": "chekhov",
    "localId": "the-duel",
    "title": "Дуэль",
    "originalTitle": "Дуэль",
    "firstPublished": 1891,
    "originalLanguage": "русский",
    "genres": [
      "повесть",
      "психологическая проза"
    ],
    "tags": [
      "нравственный выбор",
      "конфликт",
      "Кавказ",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Лаевский мечтает бежать от наскучившей связи и приморского города, но его уклончивость сталкивается с непримиримым осуждением зоолога фон Корена. Дуэль превращает личный конфликт в исследование ответственности, сострадания и возможности нравственной перемены.",
    "sourceUrl": "https://api.chekhovmuseum.com/upload/iblock/d2d/9rstowxr0fgko7arb4mf553lwfjytr3q/Sbornik_statey.pdf",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "The Duel",
        "description": "Laevsky longs to flee a failing relationship and a provincial seaside town, but his evasions collide with the zoologist von Koren's severe moral judgment. Their duel turns a personal quarrel into an inquiry about responsibility, compassion, and the possibility of ethical change.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://api.chekhovmuseum.com/upload/iblock/d2d/9rstowxr0fgko7arb4mf553lwfjytr3q/Sbornik_statey.pdf"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "Дуэль",
        "description": "Лаевский мечтает бежать от наскучившей связи и приморского города, но его уклончивость сталкивается с непримиримым осуждением зоолога фон Корена. Дуэль превращает личный конфликт в исследование ответственности, сострадания и возможности нравственной перемены.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://api.chekhovmuseum.com/upload/iblock/d2d/9rstowxr0fgko7arb4mf553lwfjytr3q/Sbornik_statey.pdf"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "Chekhov Museum Melikhovo",
        "url": "https://api.chekhovmuseum.com/upload/iblock/d2d/9rstowxr0fgko7arb4mf553lwfjytr3q/Sbornik_statey.pdf",
        "fields": [
          "identity",
          "authorship",
          "title"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      }
    ]
  },
  "russia:chekhov:the-lady-with-the-dog": {
    "legacyId": "russia:chekhov:the-lady-with-the-dog",
    "countryId": "russia",
    "writerId": "chekhov",
    "localId": "the-lady-with-the-dog",
    "title": "Дама с собачкой",
    "originalTitle": "Дама с собачкой",
    "firstPublished": 1899,
    "originalLanguage": "русский",
    "genres": [
      "рассказ",
      "психологическая проза"
    ],
    "tags": [
      "Ялта",
      "любовь",
      "двойная жизнь",
      "открытый финал",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Курортное знакомство Дмитрия Гурова и Анны Сергеевны неожиданно перерастает в чувство, которое не помещается в их прежние семейные роли. Открытый финал переносит внимание с тайного романа на трудный вопрос о честной жизни и цене перемен.",
    "sourceUrl": "https://ar.culture.ru/ru/subject/illyustracii-k-dame-s-sobachkoy",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "The Lady with the Dog",
        "description": "A holiday acquaintance between Dmitri Gurov and Anna Sergeyevna unexpectedly becomes a love that no longer fits their established family roles. The open ending shifts attention from a secret affair to the difficult question of honest life and the cost of change.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://ar.culture.ru/ru/subject/illyustracii-k-dame-s-sobachkoy",
          "https://api.chekhovmuseum.com/upload/iblock/d2d/9rstowxr0fgko7arb4mf553lwfjytr3q/Sbornik_statey.pdf"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "Дама с собачкой",
        "description": "Курортное знакомство Дмитрия Гурова и Анны Сергеевны неожиданно перерастает в чувство, которое не помещается в их прежние семейные роли. Открытый финал переносит внимание с тайного романа на трудный вопрос о честной жизни и цене перемен.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://ar.culture.ru/ru/subject/illyustracii-k-dame-s-sobachkoy",
          "https://api.chekhovmuseum.com/upload/iblock/d2d/9rstowxr0fgko7arb4mf553lwfjytr3q/Sbornik_statey.pdf"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "Artefact, Ministry of Culture of Russia",
        "url": "https://ar.culture.ru/ru/subject/illyustracii-k-dame-s-sobachkoy",
        "fields": [
          "identity",
          "authorship",
          "title",
          "publication-year"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      },
      {
        "provider": "Chekhov Museum Melikhovo",
        "url": "https://api.chekhovmuseum.com/upload/iblock/d2d/9rstowxr0fgko7arb4mf553lwfjytr3q/Sbornik_statey.pdf",
        "fields": [
          "identity",
          "authorship",
          "title"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      }
    ]
  },
  "russia:chekhov:the-man-in-a-case": {
    "legacyId": "russia:chekhov:the-man-in-a-case",
    "countryId": "russia",
    "writerId": "chekhov",
    "localId": "the-man-in-a-case",
    "title": "Человек в футляре",
    "originalTitle": "Человек в футляре",
    "firstPublished": 1898,
    "originalLanguage": "русский",
    "genres": [
      "рассказ",
      "сатирическая проза"
    ],
    "tags": [
      "страх",
      "конформизм",
      "провинция",
      "свобода",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Учитель Беликов окружает себя правилами, запретами и буквальными футлярами, а его тревога постепенно подчиняет жизнь целого города. Рассказ показывает, как страх перед свободой становится общественной привычкой и переживает самого носителя этого страха.",
    "sourceUrl": "https://chekhovmuseum.com/museum/objects/17/871?type=section",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "The Man in a Case",
        "description": "Teacher Belikov shields himself with regulations, prohibitions, and literal cases, while his anxiety gradually governs an entire town. The story shows how fear of freedom becomes a social habit that can outlive the person who embodied it.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://chekhovmuseum.com/museum/objects/17/871?type=section",
          "https://chekhovmuseum.com/en/museum/about/history"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "Человек в футляре",
        "description": "Учитель Беликов окружает себя правилами, запретами и буквальными футлярами, а его тревога постепенно подчиняет жизнь целого города. Рассказ показывает, как страх перед свободой становится общественной привычкой и переживает самого носителя этого страха.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://chekhovmuseum.com/museum/objects/17/871?type=section",
          "https://chekhovmuseum.com/en/museum/about/history"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "Chekhov Museum Melikhovo",
        "url": "https://chekhovmuseum.com/en/museum/about/history",
        "fields": [
          "identity",
          "authorship",
          "title"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      },
      {
        "provider": "Chekhov Museum Melikhovo",
        "url": "https://chekhovmuseum.com/museum/objects/17/871?type=section",
        "fields": [
          "identity",
          "authorship",
          "title",
          "publication-year"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      }
    ]
  },
  "russia:chekhov:uncle-vanya": {
    "legacyId": "russia:chekhov:uncle-vanya",
    "countryId": "russia",
    "writerId": "chekhov",
    "localId": "uncle-vanya",
    "title": "Дядя Ваня",
    "originalTitle": "Дядя Ваня",
    "firstPublished": 1897,
    "originalLanguage": "русский",
    "genres": [
      "пьеса",
      "драма"
    ],
    "tags": [
      "усадьба",
      "несбывшаяся жизнь",
      "труд",
      "любовь",
      "редакционно проверено",
      "обложка из пользовательского редакционного архива 2026-08-20"
    ],
    "description": "Войницкий и Соня годами содержат имение профессора Серебрякова, пока его приезд не обнажает чувство напрасно прожитой жизни и безответную любовь. Чеховская драма соединяет бытовой конфликт с темами труда, утраты надежд и тихой выносливости.",
    "sourceUrl": "https://chekhovmuseum.com/museum/objects/17/871?type=section",
    "editorialStatus": "verified",
    "reviewedAt": "2026-08-20",
    "translations": {
      "en": {
        "locale": "en",
        "title": "Uncle Vanya",
        "description": "Voynitsky and Sonya have spent years sustaining Professor Serebryakov's estate, until his visit exposes their sense of wasted life and unreturned love. Chekhov's drama joins domestic conflict to questions of labor, lost hope, and quiet endurance.",
        "sourceLanguage": "en",
        "status": "verified",
        "sourceUrls": [
          "https://chekhovmuseum.com/museum/objects/17/871?type=section",
          "https://chekhovmuseum.com/en/museum/about/history"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      },
      "ru": {
        "locale": "ru",
        "title": "Дядя Ваня",
        "description": "Войницкий и Соня годами содержат имение профессора Серебрякова, пока его приезд не обнажает чувство напрасно прожитой жизни и безответную любовь. Чеховская драма соединяет бытовой конфликт с темами труда, утраты надежд и тихой выносливости.",
        "sourceLanguage": "ru",
        "status": "verified",
        "sourceUrls": [
          "https://chekhovmuseum.com/museum/objects/17/871?type=section",
          "https://chekhovmuseum.com/en/museum/about/history"
        ],
        "method": "editorial-original",
        "reviewedAt": "2026-08-20"
      }
    },
    "sources": [
      {
        "provider": "Chekhov Museum Melikhovo",
        "url": "https://chekhovmuseum.com/en/museum/about/history",
        "fields": [
          "identity",
          "authorship",
          "title"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      },
      {
        "provider": "Chekhov Museum Melikhovo",
        "url": "https://chekhovmuseum.com/museum/objects/17/871?type=section",
        "fields": [
          "identity",
          "authorship",
          "title",
          "publication-year"
        ],
        "usage": "reference-only",
        "retrievedAt": "2026-08-20"
      }
    ]
  }
} as const;
