// Generated by scripts/export-published-content.mjs. Do not edit by hand.
// Published literary-work records saved in the normalized CMS library.
export const cmsLiteraryWorksByLegacyId = {} as const;
