// Generated by scripts/export-published-content.mjs.
// The empty snapshot is replaced during a production build with configured Supabase variables.
export const cmsSiteContent = {
  generatedAt: null,
  homepageBlocks: [],
  banners: [],
  navigationMenus: [],
  pages: [],
  redirects: [],
} as const;
