// Generated by scripts/export-published-content.mjs. Do not edit by hand.
// Public homepage, navigation and page metadata exported through read-only RLS policies.
export const cmsSiteContent = {
  "generatedAt": "2026-08-13T08:11:37.158Z",
  "homepageBlocks": [
    {
      "id": "df26686c-1d1b-4dbf-b3c2-ee425c4d2e1e",
      "type": "hero",
      "title": "Литература - это целый мир!",
      "settings": {
        "eyebrow": "Журнал о литературе и искусстве слова",
        "buttonUrl": "#atlas",
        "articleIds": [],
        "buttonText": "Открыть глобус",
        "description": "Статьи, биографии, редкие книги и интерактивная литературная энциклопедия стран мира - всё в одном редакционном пространстве.",
        "coreSectionKey": "hero"
      },
      "displayOrder": 10,
      "backgroundStyle": "violet",
      "backgroundMediaId": null,
      "backgroundImageUrl": "",
      "updatedAt": "2026-08-08T12:32:49.284374+00:00"
    },
    {
      "id": "64fd5508-ab91-4440-bbc1-f00c1c367e62",
      "type": "literary-map",
      "title": "Литературная планета",
      "settings": {
        "eyebrow": "Интерактивная энциклопедия",
        "buttonUrl": "#atlas",
        "articleIds": [],
        "buttonText": "",
        "description": "Выберите страну на старинном интерактивном глобусе - откроются карточки писателей, произведения и проверенная редакционная справка.",
        "coreSectionKey": "atlas"
      },
      "displayOrder": 20,
      "backgroundStyle": "violet",
      "backgroundMediaId": null,
      "backgroundImageUrl": "",
      "updatedAt": "2026-08-11T14:42:09.058734+00:00"
    },
    {
      "id": "4c4e7893-69f3-45d3-aa48-3ee7452aea19",
      "type": "book-vs-screen",
      "title": "Книга месяца",
      "settings": {
        "eyebrow": "Выбор энциклопедии",
        "buttonUrl": "#book-day",
        "articleIds": [],
        "buttonText": "О книге",
        "description": "Каждый месяц редакция выбирает новое знаковое произведение.",
        "coreSectionKey": "book-month"
      },
      "displayOrder": 30,
      "backgroundStyle": "paper",
      "backgroundMediaId": null,
      "backgroundImageUrl": "",
      "updatedAt": "2026-08-08T12:20:24.915734+00:00"
    },
    {
      "id": "b4daeef3-3997-472f-9505-a2190294180e",
      "type": "text",
      "title": "Как мы проверяем материалы",
      "settings": {
        "eyebrow": "Открытая редакция",
        "buttonUrl": "mailto:probperasite@yandex.ru?subject=Исправление%20в%20материале",
        "articleIds": [],
        "buttonText": "Сообщить об ошибке",
        "description": "Источники, права на изображения и история исправлений доступны нашему читателю.",
        "coreSectionKey": "trust"
      },
      "displayOrder": 90,
      "backgroundStyle": "violet",
      "backgroundMediaId": null,
      "backgroundImageUrl": "",
      "updatedAt": "2026-08-08T12:19:35.791006+00:00"
    }
  ],
  "siteCopy": {
    "ru": {},
    "en": {}
  },
  "banners": [],
  "navigationMenus": [
    {
      "id": "a4623064-7264-42b3-86e6-d002096e9414",
      "name": "Меню подвала",
      "location": "footer",
      "items": []
    },
    {
      "id": "886cb200-27fc-47c3-9981-3fdf8cf1047d",
      "name": "Верхнее меню",
      "location": "header",
      "items": []
    }
  ],
  "pages": [],
  "redirects": [
    {
      "sourcePath": "/stati/folklor-i-mifologiya/13-po-nastoyaschemu-zhutkih-skazok-bratev-grimm-kotorye-povergnut-vas-v-shok-14fm8t",
      "destinationPath": "/stati/folklor-i-mifologiya/13-po-nastoyaschemu-zhutkih-skazok-bratev-grimm-kotorye-povergnut-vas-v-shok",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/13-po-nastoyaschemu-zhutkih-skazok-bratev-grimm-kotorye-povergnut-vas-v-shok-chast-2-12romo",
      "destinationPath": "/stati/folklor-i-mifologiya/13-po-nastoyaschemu-zhutkih-skazok-bratev-grimm-kotorye-povergnut-vas-v-shok-chast-2",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/13-po-nastoyaschemu-zhutkih-skazok-bratev-grimm-kotorye-povergnut-vas-v-shok-chast-3-131o8c",
      "destinationPath": "/stati/folklor-i-mifologiya/13-po-nastoyaschemu-zhutkih-skazok-bratev-grimm-kotorye-povergnut-vas-v-shok-chast-3",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/a-s-pushkin-skazka-o-mertvoy-tsarevne-i-semi-bogatyryah-korni-skazki-i-vzaimosvyaz-s-obryadovym-folklorom-i-mifologiey-14plui",
      "destinationPath": "/stati/folklor-i-mifologiya/a-s-pushkin-skazka-o-mertvoy-tsarevne-i-semi-bogatyryah-korni-skazki-i-vzaimosvyaz-s-obryadovym-folklorom-i-mifologiey",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/baba-yaga-ejco7q",
      "destinationPath": "/stati/folklor-i-mifologiya/baba-yaga",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/bereginya-16zqj4",
      "destinationPath": "/stati/folklor-i-mifologiya/bereginya",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/ded-moroz-fdbhan",
      "destinationPath": "/stati/folklor-i-mifologiya/ded-moroz",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/domovoy-dzdgts",
      "destinationPath": "/stati/folklor-i-mifologiya/domovoy",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/izvestnye-personazhi-slavyanskogo-folklora-koschey-bessmertnyy-etc9wp",
      "destinationPath": "/stati/folklor-i-mifologiya/izvestnye-personazhi-slavyanskogo-folklora-koschey-bessmertnyy",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/kikimora-hv7wje",
      "destinationPath": "/stati/folklor-i-mifologiya/kikimora",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/krasnaya-shapochka-vzaimosvyaz-skazki-s-ustnym-i-obryadovym-folklorom-145mn4",
      "destinationPath": "/stati/folklor-i-mifologiya/krasnaya-shapochka-vzaimosvyaz-skazki-s-ustnym-i-obryadovym-folklorom",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/leshiy-fxaool",
      "destinationPath": "/stati/folklor-i-mifologiya/leshiy",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/poludnitsa-183oxw",
      "destinationPath": "/stati/folklor-i-mifologiya/poludnitsa",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/rusalka-17tpc7",
      "destinationPath": "/stati/folklor-i-mifologiya/rusalka",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/solovey-razboynik-obraz-personazha-v-bylinah-i-ego-vzaimosvyaz-s-folklorom-i-legendami-drevnosti-16pqxf",
      "destinationPath": "/stati/folklor-i-mifologiya/solovey-razboynik-obraz-personazha-v-bylinah-i-ego-vzaimosvyaz-s-folklorom-i-legendami-drevnosti",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/upyr-18dojl",
      "destinationPath": "/stati/folklor-i-mifologiya/upyr",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/upyr-18dojl-kopiya-e6cqx-kopiya-6whvd",
      "destinationPath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-ambroz-birs",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/upyr-kopiya",
      "destinationPath": "/stati/folklor-i-mifologiya/tugarin-zmeevich-obraz-personazha-v-bylinah-i-ego-svyaz-s-folklorom",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/viy-18no5a",
      "destinationPath": "/stati/folklor-i-mifologiya/viy",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/vodyanoy-e9d2ir",
      "destinationPath": "/stati/folklor-i-mifologiya/vodyanoy",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/zhar-ptitsa-i57i8d",
      "destinationPath": "/stati/folklor-i-mifologiya/zhar-ptitsa",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/folklor-i-mifologiya/zmey-gorynych-f3bvlo",
      "destinationPath": "/stati/folklor-i-mifologiya/zmey-gorynych",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/15-ekranizatsiy-klassicheskih-romanov-kotorye-deystvitelno-udalis-chast-2-cxyde0",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/15-ekranizatsiy-klassicheskih-romanov-kotorye-deystvitelno-udalis-chast-2",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/15-ekranizatsiy-klassicheskih-romanov-kotorye-deystvitelno-udalis-drx6gx",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/15-ekranizatsiy-klassicheskih-romanov-kotorye-deystvitelno-udalis",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/desyat-luchshih-filmov-xxi-veka-ekranizatsiy-mirovyh-bestsellerov-kotorye-opredelenno-stoyat-vashego-vremeni-chast-1-1ggult",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/desyat-luchshih-filmov-xxi-veka-ekranizatsiy-mirovyh-bestsellerov-kotorye-opredelenno-stoyat-vashego-vremeni-chast-1",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/desyat-luchshih-filmov-xxi-veka-ekranizatsiy-mirovyh-bestsellerov-kotorye-opredelenno-stoyat-vashego-vremeni-chast-2-1fmvsr",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/desyat-luchshih-filmov-xxi-veka-ekranizatsiy-mirovyh-bestsellerov-kotorye-opredelenno-stoyat-vashego-vremeni-chast-2",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/desyat-luchshih-filmov-xxi-veka-ekranizatsiy-mirovyh-bestsellerov-kotorye-opredelenno-stoyat-vashego-vremeni-chast-3-1g6v04",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/desyat-luchshih-filmov-xxi-veka-ekranizatsiy-mirovyh-bestsellerov-kotorye-opredelenno-stoyat-vashego-vremeni-chast-3",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/desyat-luchshih-filmov-xxi-veka-ekranizatsiy-mirovyh-bestsellerov-kotorye-opredelenno-stoyat-vashego-vremeni-chast-3-kopiya",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/desyat-luchshih-filmov-xxi-veka-ekranizatsiy-mirovyh-bestsellerov-kotorye-opredelenno-stoyat-vashego-vremeni-chast-4",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-1408-1692w4",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-1408",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-boytsovskiy-klub-1wgzlm",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-boytsovskiy-klub",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-forrest-gamp-1vx0e8",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-forrest-gamp",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-grinch-pohititel-rozhdestva-1x0ysz",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-grinch-pohititel-rozhdestva",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-o-myshah-i-lyudyah-15z3af",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-o-myshah-i-lyudyah",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-oblachnyy-atlas-1y4x7r",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-oblachnyy-atlas",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-park-yurskogo-perioda-15f432",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-park-yurskogo-perioda",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-starikam-tut-ne-mesto-1w6zzx",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-starikam-tut-ne-mesto",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-strah-i-nenavist-v-las-vegase-1wqz7a",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-strah-i-nenavist-v-las-vegase",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-velikiy-getsbi-1xayeo",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-velikiy-getsbi",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-voyna-mirov-1xky0d",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-voyna-mirov",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-ya-legenda-1xuxm2",
      "destinationPath": "/stati/kniga-i-ekranizatsiya/kniga-i-ekranizatsiya-ya-legenda",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/10-vydayuschihsya-knig-xxi-veka-ostavivshih-sled-v-mirovoy-literature-1dg8sy",
      "destinationPath": "/stati/knizhnyy-gid/10-vydayuschihsya-knig-xxi-veka-ostavivshih-sled-v-mirovoy-literature",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/15-luchshih-hudozhestvennyh-knig-o-piratah-kvfvng",
      "destinationPath": "/stati/knizhnyy-gid/15-luchshih-hudozhestvennyh-knig-o-piratah",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/desyat-luchshih-knig-dzheka-londona-1usmnc",
      "destinationPath": "/stati/knizhnyy-gid/desyat-luchshih-knig-dzheka-londona",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/desyat-romanov-kotorye-chitayutsya-na-odnom-dyhanii-chast-2-zwnq0t",
      "destinationPath": "/stati/knizhnyy-gid/desyat-romanov-kotorye-chitayutsya-na-odnom-dyhanii-chast-2",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/desyat-romanov-kotorye-chitayutsya-na-odnom-dyhanii-chast-3-zmo4bu",
      "destinationPath": "/stati/knizhnyy-gid/desyat-romanov-kotorye-chitayutsya-na-odnom-dyhanii-chast-3",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/desyat-romanov-kotorye-chitayutsya-na-odnom-dyhanii-chast-4-y8q3uz",
      "destinationPath": "/stati/knizhnyy-gid/desyat-romanov-kotorye-chitayutsya-na-odnom-dyhanii-chast-4",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/desyat-romanov-kotorye-chitayutsya-na-odnom-dyhanii-chast-5-xyqi60",
      "destinationPath": "/stati/knizhnyy-gid/desyat-romanov-kotorye-chitayutsya-na-odnom-dyhanii-chast-5",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/desyat-romanov-kotorye-chitayutsya-na-odnom-dyhanii-chast-6-yspb8x",
      "destinationPath": "/stati/knizhnyy-gid/desyat-romanov-kotorye-chitayutsya-na-odnom-dyhanii-chast-6",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/desyat-romanov-kotorye-chitayutsya-na-odnom-dyhanii-z2owxw",
      "destinationPath": "/stati/knizhnyy-gid/desyat-romanov-kotorye-chitayutsya-na-odnom-dyhanii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-1-13mhlp",
      "destinationPath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-1",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-2-14gges",
      "destinationPath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-2",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-3-146gt3",
      "destinationPath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-3",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-4-12sism",
      "destinationPath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-4",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-5-12ij6y",
      "destinationPath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-5",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-6-13ci00",
      "destinationPath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-6",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-7-132ieb",
      "destinationPath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-7",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-8-11okdv",
      "destinationPath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-8",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-9-11eks6",
      "destinationPath": "/stati/knizhnyy-gid/sem-nepopulyarnyh-shedevrov-velikih-pisateley-o-kotoryh-i-vy-navernyaka-ne-slyshali-chast-9",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-istorii/esse-na-temu-moe-pervoe-znakomstvo-s-poeziey-uw8442",
      "destinationPath": "/stati/literaturnye-istorii/esse-na-temu-moe-pervoe-znakomstvo-s-poeziey",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1901-god-rene-syulli-pryudom-laureat-nobelevskoy-premii-po-literature-1q07jj",
      "destinationPath": "/stati/literaturnye-premii/1901-god-rene-syulli-pryudom-laureat-nobelevskoy-premii-po-literature",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1902-god-teodor-mommzen-laureat-nobelevskoy-premii-po-literature-1qa758",
      "destinationPath": "/stati/literaturnye-premii/1902-god-teodor-mommzen-laureat-nobelevskoy-premii-po-literature",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1903-god-bernsterne-bernson-laureat-nobelevskoy-premii-1pg8c5",
      "destinationPath": "/stati/literaturnye-premii/1903-god-bernsterne-bernson-laureat-nobelevskoy-premii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1904-god-hose-echegarae-i-eysagirre-i-frederik-mistral-laureaty-nobelevskoy-premii-1pq7xu",
      "destinationPath": "/stati/literaturnye-premii/1904-god-hose-echegarae-i-eysagirre-i-frederik-mistral-laureaty-nobelevskoy-premii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1905-god-genrik-senkevich-laureat-nobelevskoy-premii-1ow94r",
      "destinationPath": "/stati/literaturnye-premii/1905-god-genrik-senkevich-laureat-nobelevskoy-premii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1906-god-dzhozue-karduchchi-laureat-nobelevskoy-premii-1p68qg",
      "destinationPath": "/stati/literaturnye-premii/1906-god-dzhozue-karduchchi-laureat-nobelevskoy-premii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1907-god-redyard-kipling-laureat-nobelevskoy-premii-1oc9xd",
      "destinationPath": "/stati/literaturnye-premii/1907-god-redyard-kipling-laureat-nobelevskoy-premii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1908-god-rudolf-eyken-laureat-nobelevskoy-premii-1om9j2",
      "destinationPath": "/stati/literaturnye-premii/1908-god-rudolf-eyken-laureat-nobelevskoy-premii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1909-god-selma-lagerlef-laureat-nobelevskoy-premii-1v1rkb",
      "destinationPath": "/stati/literaturnye-premii/1909-god-selma-lagerlef-laureat-nobelevskoy-premii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1910-god-paul-yohan-lyudvig-fon-heyze-laureat-nobelevskoy-premii-1urrym",
      "destinationPath": "/stati/literaturnye-premii/1910-god-paul-yohan-lyudvig-fon-heyze-laureat-nobelevskoy-premii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1911-god-moris-meterlink-laureat-nobelevskoy-premii-1vlqrp",
      "destinationPath": "/stati/literaturnye-premii/1911-god-moris-meterlink-laureat-nobelevskoy-premii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1912-god-gerhart-gauptman-laureat-nobelevskoy-premii-1vbr60",
      "destinationPath": "/stati/literaturnye-premii/1912-god-gerhart-gauptman-laureat-nobelevskoy-premii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1913-god-rabindranat-tagor-laureat-nobelevskoy-premii-1txt5j",
      "destinationPath": "/stati/literaturnye-premii/1913-god-rabindranat-tagor-laureat-nobelevskoy-premii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1915-god-romen-rollan-laureat-nobelevskoy-premii-1tntju",
      "destinationPath": "/stati/literaturnye-premii/1915-god-romen-rollan-laureat-nobelevskoy-premii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1916-god-verner-fon-heydenstam-laureat-nobelevskoy-premii-1uhscx",
      "destinationPath": "/stati/literaturnye-premii/1916-god-verner-fon-heydenstam-laureat-nobelevskoy-premii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1917-god-karl-adolf-gellerup-i-henrik-pontoppidan-laureaty-nobelevskoy-premii-po-literature-1u7sr8",
      "destinationPath": "/stati/literaturnye-premii/1917-god-karl-adolf-gellerup-i-henrik-pontoppidan-laureaty-nobelevskoy-premii-po-literature",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1919-god-karl-fridrih-georg-shpitteler-laureat-nobelevskoy-premii-po-literature-1stuqr",
      "destinationPath": "/stati/literaturnye-premii/1919-god-karl-fridrih-georg-shpitteler-laureat-nobelevskoy-premii-po-literature",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1920-god-knut-gamsun-laureat-nobelevskoy-premii-po-literature-1sjv52",
      "destinationPath": "/stati/literaturnye-premii/1920-god-knut-gamsun-laureat-nobelevskoy-premii-po-literature",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1921-god-anatol-frans-laureat-nobelevskoy-premii-po-literature-qj44jg",
      "destinationPath": "/stati/literaturnye-premii/1921-god-anatol-frans-laureat-nobelevskoy-premii-po-literature",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1922-god-hasinto-benavente-i-martines-laureat-nobelevskoy-premii-po-literature-qt3q8f",
      "destinationPath": "/stati/literaturnye-premii/1922-god-hasinto-benavente-i-martines-laureat-nobelevskoy-premii-po-literature",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/1923-god-uilyam-batler-yeyts-laureat-nobelevskoy-premii-po-literature-r33bxe",
      "destinationPath": "/stati/literaturnye-premii/1923-god-uilyam-batler-yeyts-laureat-nobelevskoy-premii-po-literature",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/dublinskaya-literaturnaya-premiya-1ecxy2",
      "destinationPath": "/stati/literaturnye-premii/dublinskaya-literaturnaya-premiya",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/natsionalnaya-knizhnaya-premiya-ssha-gy3xgx",
      "destinationPath": "/stati/literaturnye-premii/natsionalnaya-knizhnaya-premiya-ssha",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/nobelevskaya-premiya-istoriya-uchrezhdeniya-nagrady-i-primechatelnye-fakty-1qu6cm",
      "destinationPath": "/stati/literaturnye-premii/nobelevskaya-premiya-istoriya-uchrezhdeniya-nagrady-i-primechatelnye-fakty",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/premiya-edgara-allana-po-go4bry",
      "destinationPath": "/stati/literaturnye-premii/premiya-edgara-allana-po",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/premiya-frantsa-kafki-1cyzxl",
      "destinationPath": "/stati/literaturnye-premii/premiya-frantsa-kafki",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/premiya-georga-byuhnera-h83j5w",
      "destinationPath": "/stati/literaturnye-premii/premiya-georga-byuhnera",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/premiya-hyugo-1e2ycd",
      "destinationPath": "/stati/literaturnye-premii/premiya-hyugo",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/premiya-imeni-gansa-hristiana-andersena-1cf0q8",
      "destinationPath": "/stati/literaturnye-premii/premiya-imeni-gansa-hristiana-andersena",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/premiya-kamoensa-i22c8t",
      "destinationPath": "/stati/literaturnye-premii/premiya-kamoensa",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/premiya-migel-de-servantes-1cp0bw",
      "destinationPath": "/stati/literaturnye-premii/premiya-migel-de-servantes",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/premiya-noyshtadta-1fqvyj",
      "destinationPath": "/stati/literaturnye-premii/premiya-noyshtadta",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/premiya-pen-folknera-hi34uv",
      "destinationPath": "/stati/literaturnye-premii/premiya-pen-folknera",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/premiya-printsessy-asturiyskoy-1g0vk8",
      "destinationPath": "/stati/literaturnye-premii/premiya-printsessy-asturiyskoy",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/premiya-renodo-hs2qju",
      "destinationPath": "/stati/literaturnye-premii/premiya-renodo",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/premiya-strega-1d8zja",
      "destinationPath": "/stati/literaturnye-premii/premiya-strega",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/literaturnye-premii/pulittserovskaya-premiya-1dsyqo",
      "destinationPath": "/stati/literaturnye-premii/pulittserovskaya-premiya",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/a-o-eksvemelin-piraty-ameriki-wq2lkf",
      "destinationPath": "/stati/mnenie-o-knige/a-o-eksvemelin-piraty-ameriki",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/daniel-defo-vseobschaya-istoriya-piratstva-w63e6h",
      "destinationPath": "/stati/mnenie-o-knige/daniel-defo-vseobschaya-istoriya-piratstva",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/kristofer-hedfild-rukovodstvo-astronavta-po-zhizni-na-zemle-wg2zvg",
      "destinationPath": "/stati/mnenie-o-knige/kristofer-hedfild-rukovodstvo-astronavta-po-zhizni-na-zemle",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/mnenie-o-knige-anri-barbyus-ogon-1bzbxw",
      "destinationPath": "/stati/mnenie-o-knige/mnenie-o-knige-anri-barbyus-ogon",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/mnenie-o-knige-brem-stoker-drakula-1ctaqy",
      "destinationPath": "/stati/mnenie-o-knige/mnenie-o-knige-brem-stoker-drakula",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/mnenie-o-knige-devid-mitchell-oblachnyy-atlas-vc4l3k",
      "destinationPath": "/stati/mnenie-o-knige/mnenie-o-knige-devid-mitchell-oblachnyy-atlas",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/mnenie-o-knige-devida-mitchella-pod-znakom-chernogo-lebedya-1dn9k1",
      "destinationPath": "/stati/mnenie-o-knige/mnenie-o-knige-devida-mitchella-pod-znakom-chernogo-lebedya",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/mnenie-o-knige-devida-mitchella-utopiya-avenyu-1er7yt",
      "destinationPath": "/stati/mnenie-o-knige/mnenie-o-knige-devida-mitchella-utopiya-avenyu",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/mnenie-o-knige-dzh-r-r-tolkin-pisma-rozhdestvenskogo-deda-1dx95q",
      "destinationPath": "/stati/mnenie-o-knige/mnenie-o-knige-dzh-r-r-tolkin-pisma-rozhdestvenskogo-deda",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/mnenie-o-knige-dzhek-london-belyy-klyk-z7z0t6",
      "destinationPath": "/stati/mnenie-o-knige/mnenie-o-knige-dzhek-london-belyy-klyk",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/mnenie-o-knige-dzhek-london-morskoy-volk-zhymi5",
      "destinationPath": "/stati/mnenie-o-knige/mnenie-o-knige-dzhek-london-morskoy-volk",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/mnenie-o-knige-gerberta-uellsa-voyna-v-vozduhe-jycxbu",
      "destinationPath": "/stati/mnenie-o-knige/mnenie-o-knige-gerberta-uellsa-voyna-v-vozduhe",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/mnenie-o-knige-hantera-tompsona-angely-ada-jodbmv",
      "destinationPath": "/stati/mnenie-o-knige/mnenie-o-knige-hantera-tompsona-angely-ada",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/mnenie-o-knige-haruki-murakami-norvezhskiy-les-1cjb59",
      "destinationPath": "/stati/mnenie-o-knige/mnenie-o-knige-haruki-murakami-norvezhskiy-les",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/mnenie-o-knige-kuda-privodyat-mechty-richarda-matesona-1f17ki",
      "destinationPath": "/stati/mnenie-o-knige/mnenie-o-knige-kuda-privodyat-mechty-richarda-matesona",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/mnenie-o-knige-lorana-gunelya-bog-puteshestvuet-inkognito-jedpxw",
      "destinationPath": "/stati/mnenie-o-knige/mnenie-o-knige-lorana-gunelya-bog-puteshestvuet-inkognito",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/mnenie-o-knige-mario-pyuzo-shest-mogil-na-puti-v-myunhen-1c9bjk",
      "destinationPath": "/stati/mnenie-o-knige/mnenie-o-knige-mario-pyuzo-shest-mogil-na-puti-v-myunhen",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/mnenie-o-knige-ostrov-oldosa-haksli-k8cj0t",
      "destinationPath": "/stati/mnenie-o-knige/mnenie-o-knige-ostrov-oldosa-haksli",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/posledniy-roman-dzheka-londona-byuro-zakaznyh-ubiystv-x0279e",
      "destinationPath": "/stati/mnenie-o-knige/posledniy-roman-dzheka-londona-byuro-zakaznyh-ubiystv",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/s-i-ozhegov-tolkovyy-slovar-russkogo-yazyka-vm46sj",
      "destinationPath": "/stati/mnenie-o-knige/s-i-ozhegov-tolkovyy-slovar-russkogo-yazyka",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/mnenie-o-knige/sbornik-rasskazov-frensisa-skotta-fitsdzheralda-pribrezhnyy-pirat-vw3shi",
      "destinationPath": "/stati/mnenie-o-knige/sbornik-rasskazov-frensisa-skotta-fitsdzheralda-pribrezhnyy-pirat",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/o-literature/biblioteka-buduschego-proizvedeniya-imenityh-avtorov-kotorye-uvidyat-svet-lish-cherez-100-let-tazs5",
      "destinationPath": "/stati/o-literature/biblioteka-buduschego-proizvedeniya-imenityh-avtorov-kotorye-uvidyat-svet-lish-cherez-100-let",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/o-literature/desyat-knig-kotorye-opredelenno-podaryat-vam-novogodnee-i-rozhdestvenskoe-nastroenie-1y6hfl",
      "destinationPath": "/stati/o-literature/desyat-knig-kotorye-opredelenno-podaryat-vam-novogodnee-i-rozhdestvenskoe-nastroenie",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-a-p-chehov-1ay6cx",
      "destinationPath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-a-p-chehov",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-anri-barbyus-1bi5kb",
      "destinationPath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-anri-barbyus",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-dzhek-london-1ae75k",
      "destinationPath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-dzhek-london",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-edgar-allan-po-5akf2n",
      "destinationPath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-edgar-allan-po",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-ernest-heminguey-1ek16y",
      "destinationPath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-ernest-heminguey",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-gerbert-uells-1cc4de",
      "destinationPath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-gerbert-uells",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-horhe-luis-borhes-1ao6r8",
      "destinationPath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-horhe-luis-borhes",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-l-n-tolstoy-1ea1l9",
      "destinationPath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-l-n-tolstoy",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-mark-tven-1bs560",
      "destinationPath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-mark-tven",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-roald-dal-50ktdo",
      "destinationPath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-roald-dal",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-sinkler-lyuis-1b85ym",
      "destinationPath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-sinkler-lyuis",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/o-literature/upadok-mediakultury-osnovnye-faktory-degradatsii-kino-i-igr-1z0g8o",
      "destinationPath": "/stati/o-literature/upadok-mediakultury-osnovnye-faktory-degradatsii-kino-i-igr",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-avstraliya-1aekt8",
      "destinationPath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-avstraliya",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-braziliya-1bij80",
      "destinationPath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-braziliya",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-indiya-1ayk0m",
      "destinationPath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-indiya",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-italiya-18gnld",
      "destinationPath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-italiya",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-kitay-1c2ife",
      "destinationPath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-kitay",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-meksika-1b8jmb",
      "destinationPath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-meksika",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-norvegiya-52yake",
      "destinationPath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-norvegiya",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-shvetsiya-4syovf",
      "destinationPath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-shvetsiya",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-turtsiya-186nzo",
      "destinationPath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-turtsiya",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-yaponiya-1bsitp",
      "destinationPath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-yaponiya",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-yuar-4iz36g",
      "destinationPath": "/stati/pisateli-mira/literaturnaya-karta-mira-7-znakovyh-pisateley-proslavivshih-svoyu-rodinu-yuar",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/nepriznannye-sovremennikami-genii-literatury-emili-dikinson-1gcvfb",
      "destinationPath": "/stati/pisateli-mira/nepriznannye-sovremennikami-genii-literatury-emili-dikinson",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/nepriznannye-sovremennikami-genii-literatury-fernandu-pessoa-1h6u8d",
      "destinationPath": "/stati/pisateli-mira/nepriznannye-sovremennikami-genii-literatury-fernandu-pessoa",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/nepriznannye-sovremennikami-genii-literatury-german-melvill-1g2vtm",
      "destinationPath": "/stati/pisateli-mira/nepriznannye-sovremennikami-genii-literatury-german-melvill",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/nepriznannye-sovremennikami-genii-literatury-marsel-prust-1fsw7x",
      "destinationPath": "/stati/pisateli-mira/nepriznannye-sovremennikami-genii-literatury-marsel-prust",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/nepriznannye-sovremennikami-genii-literatury-stendal-1f8x0j",
      "destinationPath": "/stati/pisateli-mira/nepriznannye-sovremennikami-genii-literatury-stendal",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/nepriznannye-sovremennikami-genii-literatury-uolt-uitmen-1gmv0z",
      "destinationPath": "/stati/pisateli-mira/nepriznannye-sovremennikami-genii-literatury-uolt-uitmen",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/russkie-klassiki-i-ih-professii-6c1e75",
      "destinationPath": "/stati/pisateli-mira/russkie-klassiki-i-ih-professii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/russkie-klassiki-i-ih-professii-chast-2-5s26t7",
      "destinationPath": "/stati/pisateli-mira/russkie-klassiki-i-ih-professii-chast-2",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/zarubezhnye-klassiki-literatury-i-ih-professii-5i2l48",
      "destinationPath": "/stati/pisateli-mira/zarubezhnye-klassiki-literatury-i-ih-professii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/zarubezhnye-klassiki-literatury-i-ih-professii-chast-2-7607a2",
      "destinationPath": "/stati/pisateli-mira/zarubezhnye-klassiki-literatury-i-ih-professii-chast-2",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/pisateli-mira/zarubezhnye-klassiki-literatury-i-ih-professii-chast-3-7fzsz1",
      "destinationPath": "/stati/pisateli-mira/zarubezhnye-klassiki-literatury-i-ih-professii-chast-3",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/russkiy-yazyk/15-krylatyh-vyrazheniy-prishedshih-k-nam-iz-drevnegrecheskoy-mifologii-1ibl8w",
      "destinationPath": "/stati/russkiy-yazyk/15-krylatyh-vyrazheniy-prishedshih-k-nam-iz-drevnegrecheskoy-mifologii",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/russkiy-yazyk/popolnyaem-slovarnyy-zapas-vmeste-25-unikalnyh-i-redkih-slov-kotorymi-vy-raznoobrazite-svoyu-rech-a-1rjm2m",
      "destinationPath": "/stati/russkiy-yazyk/popolnyaem-slovarnyy-zapas-vmeste-25-unikalnyh-i-redkih-slov-kotorymi-vy-raznoobrazite-svoyu-rech-a",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/russkiy-yazyk/popolnyaem-slovarnyy-zapas-vmeste-25-unikalnyh-i-redkih-slov-kotorymi-vy-raznoobrazite-svoyu-rech-b-1r9mgx",
      "destinationPath": "/stati/russkiy-yazyk/popolnyaem-slovarnyy-zapas-vmeste-25-unikalnyh-i-redkih-slov-kotorymi-vy-raznoobrazite-svoyu-rech-b",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/russkiy-yazyk/popolnyaem-slovarnyy-zapas-vmeste-25-unikalnyh-i-redkih-slov-kotorymi-vy-raznoobrazite-svoyu-rech-d-1qfnnu",
      "destinationPath": "/stati/russkiy-yazyk/popolnyaem-slovarnyy-zapas-vmeste-25-unikalnyh-i-redkih-slov-kotorymi-vy-raznoobrazite-svoyu-rech-d",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/russkiy-yazyk/popolnyaem-slovarnyy-zapas-vmeste-25-unikalnyh-i-redkih-slov-kotorymi-vy-raznoobrazite-svoyu-rech-e-zh-1q5o25",
      "destinationPath": "/stati/russkiy-yazyk/popolnyaem-slovarnyy-zapas-vmeste-25-unikalnyh-i-redkih-slov-kotorymi-vy-raznoobrazite-svoyu-rech-e-zh",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/russkiy-yazyk/popolnyaem-slovarnyy-zapas-vmeste-25-unikalnyh-i-redkih-slov-kotorymi-vy-raznoobrazite-svoyu-rech-e-zh-kopiya",
      "destinationPath": "/stati/russkiy-yazyk/popolnyaem-slovarnyy-zapas-vmeste-25-unikalnyh-i-redkih-slov-kotorymi-vy-raznoobrazite-svoyu-rech-z",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/russkiy-yazyk/popolnyaem-slovarnyy-zapas-vmeste-25-unikalnyh-i-redkih-slov-kotorymi-vy-raznoobrazite-svoyu-rech-g-1qpn9j",
      "destinationPath": "/stati/russkiy-yazyk/popolnyaem-slovarnyy-zapas-vmeste-25-unikalnyh-i-redkih-slov-kotorymi-vy-raznoobrazite-svoyu-rech-g",
      "statusCode": 301
    },
    {
      "sourcePath": "/stati/russkiy-yazyk/popolnyaem-slovarnyy-zapas-vmeste-25-unikalnyh-i-redkih-slov-kotorymi-vy-raznoobrazite-svoyu-rech-v-1qzmv8",
      "destinationPath": "/stati/russkiy-yazyk/popolnyaem-slovarnyy-zapas-vmeste-25-unikalnyh-i-redkih-slov-kotorymi-vy-raznoobrazite-svoyu-rech-v",
      "statusCode": 301
    }
  ],
  "bookEditionsByWorkId": {}
} as const;
