// Generated by scripts/export-published-content.mjs. Do not edit by hand.
// Public homepage, navigation and page metadata exported through read-only RLS policies.
export const cmsSiteContent = {
  "generatedAt": "2026-08-04T08:21:47.580Z",
  "homepageBlocks": [],
  "banners": [],
  "navigationMenus": [
    {
      "id": "a4623064-7264-42b3-86e6-d002096e9414",
      "name": "Меню подвала",
      "location": "footer",
      "items": []
    },
    {
      "id": "886cb200-27fc-47c3-9981-3fdf8cf1047d",
      "name": "Верхнее меню",
      "location": "header",
      "items": []
    }
  ],
  "pages": [],
  "redirects": [
    {
      "sourcePath": "/stati/folklor-i-mifologiya/upyr-18dojl-kopiya-e6cqx-kopiya-6whvd",
      "destinationPath": "/stati/o-literature/sem-maloizvestnyh-rasskazov-imenityh-pisateley-kotorye-sleduet-prochitat-kazhdomu-ambroz-birs",
      "statusCode": 301
    }
  ],
  "bookEditionsByWorkId": {}
} as const;
