// Generated by scripts/export-premium-translations.mjs. Do not edit by hand.
// Durable writer-profile overrides plus provenance-safe biographies.
export const cmsWriterProfileOverrides = {} as const;
